<?php
header("Content-Type: application/force-download");
header('Content-Disposition: attachment; filename=investment_orgs_sample_old.csv');
?>Headers :,Name of Investment Organizations,Description,Website,Blog,Twitter,Facebook,Email address,Year Founded,Logo,Country ,People,Status,Active?
Data Format:,[Incorporated company],[Text Description],,"[Blog URL],[Blog Feed URL]","[Twitter handler],[Twitter handler2]","[Facebook Page URL],[Facebook Page URL 2]",[General contact email address],[yyyy],,[Recognized country name],,"[""Closed""/""Live""]","[""1""/""0""]"
,BANSEA,"Has network connections to angel groups in China, India, Malaysia and Thailand, as well as close links to groups in Europe and the US.  Our members have investment experience spanning multiple sectors and a track record in building successful companies.",http://www.bansea.org/,,,,jennylaw.sg@gmail.com,2001,,Singapore,,Live,1
,SVCA,"a non-profit, private sector i",http://www.svca.org.sg/index1.htm,,,,info@svca.org.sg,1992,,Singapore,,Live,1
,Nanostart Singapore Fund,"a closed-end venture capital fund that invests in young nanotechnology companies in Singapore. The fund is a joint project of Nanostart and the National Research Foundation (NRF), an agency of the Singaporean government. Founded in 2009 it has a total investment volume of 10 million Singapore dollars and a lifetime of 10 years.",http://www.nanostart.de/index.php/en/portfolio/nanostart-asia-pacific/singapore-early-stage-venture-fund,,,,inquiry@nanostart.de,2008,,Singapore,,Live,1
,Bioveda Capital,"Invest in companies in the healthcare sector with leading market positions, proprietary technologies, and outstanding scientific and management talent.  We are a crucial business and scientific bridge between companies in the East and West, linking business and technology between two very diverse markets.",http://www.biovedavc.com/,,,,info@biovedacapital.com,,,Singapore,,Live,1
,Tamarix Capital,"Flexible in investment approach, structuring capital solutions that best meet the needs of owners and managers, while also providing optimal risk-adjusted returns for our investors. Our investments can take a variety of forms including unitranche debt, second lien debt, subordinated debt, preferred equity and common equity. Often, we will blend these securities together into one investment, providing our portfolio companies the advantage of a ""one-stop"" financial partner",http://www.tamarixcapital.com/index1.html,,,,mhauser@tamarixcapital.com,1994,,USA,,Live,1
,Extream Ventures,"an early-stage venture capital firm focused on providing funding, expertise and networks.",http://www.extreamventures.com/,,,,enquiry@extreamventures.com,2008,,Singapore,,Live,1
,Golden Gate Ventures,Golden Gate Ventures operates two tiers of investment.  Tier 1 is an accelerator program where you’ll work directly alongside a handful of other startups and 2 full-time mentors to launch your product and get it to market.  Tier 2 is a seed investment program for startups that already have a launched product and market traction.,http://goldengate.vc/,http://goldengate.vc/category/blog/,,,hello@goldengate.vc,,,Singapore,,Live,1
,Kyosei Ventures,"an Investment Holdings Company that aims to create, seed, invest and grow companies, products and services related to the Interactive Digital Media Marketing, Digital Conversion Optimizations and Analytics sectors in South-East Asia.",http://www.kyoseiventures.com/,,,https://www.facebook.com/KyoseiVentures,info@kyoseiventures.com,,,Singapore,,Live,1
, Crystal Horse Investment,"supports this initiative very much and really respects the producers drive to support the start-up eco-system in South East Asia. Crystal Horse Investments works very close with the Angels Gate Advisory board regarding the funding aspect of the entrepreneurs. From due diligence to signing the deal, we leverage on each others expertises",http://ch-investments.com.sg/wp/,,,https://www.facebook.com/crystalhorseinvestments,,,,Singapore,,Live,1
,Hina Capital Partners,one of China's leading cross border investment banking and private equity firms. ,http://www.hinagroup.com/,,,,info@hinagroup.com.cn,2003,,China,,Live,1
,MediaCorp,"Singapore’s leading media company with the most complete range of platforms, spanning television, radio, newspapers, magazines, movies, digital and out-of-home media.",http://www.mediacorp.sg/en/home,,,,,1963,,Singapore,,Live,1
,Singapore Press Holding,"Southeast Asia's leading media organisation, engaging minds and enriching lives across multiple languages and platforms.",http://www.sph.com.sg/home.shtml,,,https://www.facebook.com/officialsph,sphcorp@sph.com.sg,1984,,Singapore,,Live,1
,Sycamore Ventures,"a global investment firm with offices in the US, India, and Singapore. Collectively, our investment professionals have well over 100 years of investment experience, have invested in more than 100 companies, served on the boards of directors of over 75 companies, taken more than 20 companies public and sold or merged over 40 companies. Funds under our management invest in the US, the greater China region, and India.",http://www.sycamorevc.com/,,,,,,,Singapore,,Live,1
,Crest Capital Asia,"a specialized alternative investment firm that focuses in investment opportunities around under-served, mid-capitalization regional enterprises. With mainly Asian investor institutions, government agencies and family offices as clients, we identify and pursue investment opportunities in the region with proven business models and, in particular, those which had built intellectual properties or proprietary franchises.",http://www.crestcapitalasia.com/en/,,,,contact@crestcapitalasia.com,1987,,Singapore,,Live,1
,Henderson Equity Partners,A private equity operation of Henderson Global Investors.,http://www.henderson.com/sites/henderson/privateequity/home.aspx,,,,,,,Singapore,,Live,1
,Standard Chartered Private Equity,,http://www.standardchartered.com/en/,,@StanChart,https://www.facebook.com/StandardChartered,be.secure@sc.com,,,Singapore,,Live,1
,McAfee,"a wholly owned subsidiary of Intel Corporation (NASDAQ:INTC), is the world's largest dedicated security company. ",http://www.mcafee.com/us/,,@McAfeeBusiness,https://www.facebook.com/McAfee,,1987,,California,,Live,1
,DailyMuses,a special space for you to freely muse about your thoughts and experiences with fun and supportive people.,http://dailymus.es/,,@Dailymuses,https://www.facebook.com/dailymuses,,,,,,Live,1
,WA Police,"is one of eight police jurisdictions in Australia and is responsible for policing the world's largest single police jurisdiction covering 2.5 million square kilometres with a structure comprising three regions, 14 districts and 157 police stations.",http://www.police.wa.gov.au/,,@WA_Police,https://www.facebook.com/WA.Police,,,,Australia,,Live,1
,Accelerator Technology Holdings,"a holding company incorporated in Guernsey on 31st January, 2005, that acts through a group of companies established in Bahrain and Jordan to identify, invest in and help build best of breed ventures in the ICT value chain in the Arab world",http://www.acceleratortech.com/,,,,info@acceleratortech.com,2005,,Jordan,,Live,1
,Adventure Capital,"an Australian early-stage digital media and web 2.0 venture fund. Adventure Capital is intently focused on advancing the digital and online technology ecosystem, benefiting from Australia’s intellectual capital by providing opportunities for innovative, driven and intelligent entrepreneurs to reach their full potential.",http://adventurecapital.vc/,,@ACVenture,https://www.facebook.com/Adventurecapital,,,,Australia,,Live,1
,Angaros Group Pte Ltd," management consulting firm with an agile group of strategists, creative thinkers, designers, marketers and technologists with entrepreneurial passion",http://www.angaros.com/,,,,info@angaros.com,2006,,Singapore,,Live,1
,AngelCube,"a micro VC fund, or startup accelerator based on best of breed accelerators: Y-Combinator, Techstars, Seedcamp, 500 Start Ups and Startmate. These investment firms have now helped many startups transition from idea to valuable business and have re-energized their respective investment communities.",http://www.angelcube.com/,http://www.angelcube.com/blog/,@AngelCubeMelb,https://www.facebook.com/AngelCubeMelb,,,,Australia,,Live,1
,Angels Den Asia,,http://www.angelsden.com/Asia/,http://blog.angelsden.co.uk/,,https://www.facebook.com/AngelsDenSingapore,,,,UK,,Live,1
,Ardent Capital,"a private capital fund that guides entrepreneurs with high potential and great business ideas down the path of wealth creation by providing early stage capital, experienced advisors, technical support, key staff, and connections to resources in SE Asia. Our companies receive early-stage investment, follow on investment, and intensive expert guidance from our founders and advisors with experience in founding and exiting several internet companies in S.E. Asia.",http://www.ardentcap.com/,,,,business@ardentcap.com,,,Thailand,,Live,1
,Batavia Incubator,,http://batavia-incubator.com/,,,,info@batavia-incubator.com,,,Indonesia,,Live,1
,Beaver Lake Capital,"a privately held, entrepreneurial investment firm seeking to acquire and actively manage a single small to medium-sized business. Beaver Lake Capital will make a controlling investment in a profitable technology or technology-enabled-services company with annual revenues of $5 to $25 million and cash flows of $1.5 to $5 million, in Singapore or the region",http://beaverlakecapital.com/,,,,zz@beaverlakecapital.com,,,Singapore,,Live,1
,Cap Vista Pte Ltd," the strategic investment arm of Defence Science and Technology Agency (DSTA), a statutory board of the Singapore Ministry of Defence.",http://www.capvista.com.sg/,,,,info@capvista.com.sg,,,Singapore,,Live,1
,Dentsu Digital Holdings Inc. Singapore,,http://www.dentsu-digital.co.jp/en/,,,,info@dentsu-digital.co.jp,,,Japan,,Live,1
,DFJ VinaCapital,,http://www.dfj-vinacapital.com/,,,,,,,Vietnam,,Live,1
,Digital Media Partners Pte Ltd,a team of media entrepreneurs and investment professionals dedicated to development of digital media industry in emerging markets.,http://www.digitalmedia.vc/legal.html,,,,team@digitalmedia.vc,,,Singapore,,Live,1
,Dikaios,,http://www.dikaios.com.br/indexi.html,,,,dikaios@dikaios.com.br,2002,,Brazil,,Live,1
,DMGT International,"Operating in over 40 countries, DMGT produces high-quality content, information, analytics and events for both businesses and consumers.",http://www.dmgt.co.uk/,,@DMGTplc,,enquiries@dmgt.co.uk,1896,,UK,,Live,1
,Dutchman Capital,a Singapore-based private investment fund that invests in start-up and early-stage technology companies in the Digital Entertainment and Digital Media space.,http://dutchman-capital.com/,,,,info@dutchman-capital.com,,,Singapore,,Live,1
,Ensogo,,http://www.ensogo.com/,,@EnsogoThailand,,,,,Thailand,,Live,1
,Fatfish Medialab," first-of-a-kind digital incubator and investor in Asia that is laser-focused on a particular segment of the interactive digital media (IDM) space: mobile and social media apps. Fatfish provides a holistic approach to assist selected early-stage companies in the chosen space, enabling these fledging projects to go from concept to commercialization",http://www.fatfishlab.com/,http://www.fatfishlab.com/?p=1,@FatfishLab,,media@fatfishlab. com,,,Singapore,,Live,1
,Fundamental Capital Advisors Pte Ltd," registered investment advisor that provides multi-manager hedge fund opportunities for accredited individuals, family offices, and institutions.",http://www.fundamentallp.com/fund_login&e=1,,,,,,,California,,Live,1
,GITP Pte Ltd,invested in technology companies in various stages of development and look to add to our portfolio by working with entrepreneurs who have innovative ideas and a need for capital to move to the next stage.,http://www.gitpx.com/,,,,info@gitpx.com,,,Singapore,,Live,1
,Global Brain Corporation,"a venture capital?focusing on seed and early stage ventures. We are committed to accelerating growth of our portfolio ventures by providing not only capital, but also support to establish business models, marketing teams, sales processes and appoint executives.",http://www.globalbrains.co.jp/english/index.html,,,,,1998,,Japan,,Live,1
,GMO Internet Inc,,http://www.gmo.jp/en/,,@GMO_Group,,ir-gmo@freeml.com,,,Japan,,Live,1
,Go-Vin Holdings Pte Ltd,the investment banking & advisory (IBA) arm of GO-VIN Holdings that provides business advisory services to companies in the US & Europe and designs effective entry strategies for such companies in Asia,http://www.govinholdings.com/index.html,,,,anand@govininvest.com,,,Singapore,,Live,1
,Golden Gate Ventures,,http://goldengate.vc/,http://goldengate.vc/category/blog/,@GoldenGateVC,,hello@goldengate.vc,,,Singapore,,Live,1
,GREE Ventures Inc,,http://www.greeventures.com/en/,,,https://www.facebook.com/pages/Green-Ventures-Inc/227506710593946,info@greeventures.com,,,Japan,,Live,1
,Infocomm Investments,,http://www.infocomminvestments.com/,http://www.infocomminvestments.com/blog/,@iipl,https://www.facebook.com/pages/Infocomm-Investments-Pte-Ltd/146757218073,info@iipl.sg,1996,,Singapore,,Live,1
,Jacanda Capital, an Australian based boutique corporate advisory firm with international capabilities and strategic alliances,http://www.jacandacapital.com.au/,,,,andrew@jacandacapital.com.au,,,Australia,,Live,1
,JFDI Asia,lead people to think and act entrepreneurially by helping them to engineer innovative businesses around their ideas,http://jfdi.asia/,,@jfdiasia,https://www.facebook.com/jfdiasia,info@jfdi.asia,,,Singapore,,Live,1
,Jungle Ventures,"The firm is invested in by an active network of Asian entreprenures, tech executives and institutional investors that further support the tactical and strategic growth of the investee companies in the region and world markets.",http://www.jungle-ventures.com/,,@jungleventures,,amit@jungle-ventures.com,,,Singapore,,Live,1
,KAE Capital,"invests in early stage companies which bring about innovative solutions for the existing gaps in the markets, all backed by a great team capable to execute and build a large business.",http://www.kae-capital.com/,,,https://www.facebook.com/pages/Kae-Capital/194133543987523?sk=wall,info@kae-capital.com,,,India,,Live,1
,Lefora,,http://www.lefora.com/,http://blog.lefora.com/,@lefora,,,,,,,Live,1
,LINC 360,"focused on simplifying the user experience yet making the user more productive with their daily routine. By pioneering an integration that is simple and robust, customers can guarantee success with their CRM and Email integration.",http://www.linkpoint360.com/,,,,support@LinkPoint360.com,2001,,,,Live,1
,Lion Partners, founded on the principle that the quality of services offered by major investment banks should be available to companies that are emerging or have smaller market capitalizations which attract the interest of traditional financing sources.,http://www.lionpartnersltd.com/,,,,info@lionpartnersltd.com,,,USA,,Live,1
,MaBelle.com / CoCoon / Dorical,the sole distributor for world famous nail products- Young Nails & Hotsie Totsie in Malaysia & Singapore,http://www.mabelle.com.my/index.php/en/,,,,,,,Malaysia,,Live,1
,Makansutra,a food company that does not sell food but to promote the joy of eating,http://www.makansutra.com/index.php,,@makansutra,https://www.facebook.com/makansutra,contact@makansutra.com,1997,,Singapore,,Live,1
,Mapua Insitute of Technology,,http://www.mapua.edu.ph/,http://mit-ot.blogspot.com/,@MapuaInstitute,https://www.facebook.com/MapuaInstitute,,,,Philippines,,Live,1
,Matinda Capital,"aims to provide financial support to its investments, particularly expansion capital, together with strategic guidance and assistance through leveraging its wide network of contacts throughout Asia, Australia and the United States.",http://www.matindacapital.com/home/home.cfm,,,,simon@matindacapital.com,,,Singapore,,Live,1
,Mbounce,"strong technology platform solutions powers a wide range of services which are created, distributed, delivered and monetized globally for Brands, ODMs, IDHs, CPs, mobile advertising companies as well as social community networks. ",http://www.mbounce.com/,,,,info@mbounce.com,2001,,Hong Kong,,Live,1
,Merah Putih Incubators,,http://www.merahputih.co.id/,,@MerahPutihInc,,info@merahputih.co.id,,,Indonesia,,Live,1
,MIT Enterprise Forum Singapore,"a platform for entrepreneurial networking, inspiration and education",http://sg.mitef.org/s/1314/sub-start.aspx?gid=2&pgid=61,,@mitefsg,https://www.facebook.com/pages/MIT-Enterprise-Forum-of-Singapore/221642467333,contact@mitef.sg,,,Singapore,,Live,1
,Roland Berger Strategy Consultants,,http://www.rolandberger.com/,,@BergerNews,https://www.facebook.com/RolandBergerStrategyConsultants,,,,Singapore,,Live,1
,National Business Incubation Association,"the world’s leading organization advancing business incubation and entrepreneurship. Each year, it provides thousands of professionals with information, education, advocacy and networking resources to bring excellence to the process of assisting early-stage companies.",http://www.nbia.org/,,,https://www.facebook.com/pages/National-Business-Incubation-Association/101344409922908,info@nbia.org,,,Greece,,Live,1
,Neoteny Labs,An early stage fund focused on consumer Internet startups in Asia and the Middle East.,http://neotenylabs.com/,http://neotenylabs.com/labs/blog/,@neotenylabs,,james@neotenylabs.com,,,Singapore,,Live,1
,Newton Circus,,http://newton-circus.com/,,@NCchatter,https://www.facebook.com/pages/Newton-Circus/166921789996888,contact@newton-circus.com,,,Singapore,,Live,1
,Nokia Growth Partners,"the leading global growth stage venture firm focused on mobile technology, services and media. We invest in companies, firms, and people that are changing the face of mobility, communications, and the internet.",http://www.nokiagrowthpartners.com/,,,,ngpteam@nokiagrowthpartners.com,,,USA,,Live,1
,Open Network Lab,,http://onlab.jp/,http://onlab.jp/blog/index.html,@on_lab,https://www.facebook.com/OpenNetworkLab,,2011,,Japan,,Live,1
,Orita Sinclair,,http://www.orita-sinclair.edu.sg/,,@oritasinclair,https://www.facebook.com/Orita.Sinclair,info@orita-sinclair.edu.sg,,,Singapore,,Live,1
,Palmetto Ventures,,http://www.bcorporation.net/community/directory/palmettoventures,,@BCorporation,https://www.facebook.com/bcorporation,thelab@bcorporation.net,,,USA,,Live,1
,Plug and Play Tech Center,"a global accelerator that specializes in growing tech startups. Headquartered in Sunnyvale California, Plug and Play’s network includes over 300 tech startups, 180 investors and a community of leading Universities and Corporate partners.",http://www.plugandplaytechcenter.com/,,@PlugandPlayTC,https://www.facebook.com/plugandplaytechcenter,,,,USA,,Live,1
,Pollenizer,,http://pollenizer.com/,,@pollenizer,https://www.facebook.com/Pollenizer, info@pollenizer.com,,,Australia,,Live,1
,Preston & Walker,,http://prestonwalker.com/,,@PrestonWalker6,https://www.facebook.com/pages/Preston-Walker/324556564232143,admin@prestonwalker.com,,,Singapore,,Live,1
,RW Ventures,"a consulting firm focusing on market-based strategies for regional and community economic development. By bringing sophisticated economic analysis to urban markets, we create the information resources, products and institutions necessary to improve performance and drive inclusive economic growth. ",http://www.rw-ventures.com/,,,,,,,USA,,Live,1
,Red Dot Ventures Pte Ltd ,"seed-stage venture capital firm focused on Singapore-based high-tech startups in areas including ICT, Interactive Digital Media (IDM), MedTech, Nanotech, CleanTech, and Engineering.",http://www.reddotventures.com/,,,,contact@reddotventures.com,2011,,Singapore,,Live,1
,Right Click Capital,,http://www.rightclickcapital.com/,,,https://www.facebook.com/pages/Right-Click-Capital/117206755068565,info@rightclickcapital.com,2003,,Australia,,Live,1
,Experian,,,,,,,,,,,Live,1
,S&R Partners,,,,,,,,,,,Live,1
,Seashell Venture Partners,,,,,,,,,,,Live,1
,Shenga Coaching International,,,,,,,,,,,Live,1
,Silicon Badia Ventures,an accelerator program and technology transfer fund that is attempting to bridge the Middle East North Africa (MENA) region’s startup ecosystem to entrepreneurial ecosystems around the world.,http://www.siliconbadia.com/stories,,@siliconbadia,,info@siliconbadia.com,,,,,Live,1
,Silver Sea Asset Management,,http://www.silverseaam.com/relationship,,,,,,,Singapore,,Live,1
,SingTel,,http://info.singtel.com/,,@SingTel,https://www.facebook.com/singtel,,,,Singapore,,Live,1
,Skynet Technology Incubator,,http://skynet.vn/,,,, contact@skynet.vn,,,Vietnam,,Live,1
,Softbank China,,http://www.softbankci.com/,,,,,,,China,,Live,1
,Startup Sauna,,http://startupsauna.com/en/,http://startupsauna.com/en/blog/,@startupsauna,https://www.facebook.com/startupsauna,,2010,,Finland,,Live,1
,StartupWeekend,"global network of passionate leaders and entrepreneurs on a mission to inspire, educate, and empower individuals, teams and communities",http://startupweekend.org/,http://startupweekend.org/blog/,@StartupWeekend,https://www.facebook.com/startupweekend,,,,USA,,Live,1
,Sumitomo Corporation,"Engage in multifaceted business activities benefitting from our Integrated Corporate Strength, selling a variety of domestic products and services, conducting import/ export and trilateral business transactions, providing domestic and international business investment, and participating in numerous other profitable activities facilitated by our global network and the relationships of trust built with corporate business partners and consumers in various industrial sectors around the world.",http://www.sumitomocorp.co.jp/english/,,,,,1919,,Japan,,Live,1
,Tapestrix,"a customizable social media platform which allows corporates, brands & communities to integrate corporate identities into their own social media",http://tapestrix.net/,,@tapestrix,,info@tapestrix.net,,,Indonesia,,Live,1
,The Guthrie Group,"a leading, independent consultancy firm, focussed on the initiation, facilitation and completion of transaction",http://www.theguthriegroup.co.uk/,,,,enquiries@theguthriegroup.co.uk,1997,,UK,,Live,1
,TPG Capital,,http://www.tpg.com/,,@TPGCapital ,,info@tpg.com,1992,,USA,,Live,1
,Vanda Venture,,http://vandaventure.com/,,,,,,,,,Live,1
,WaveMaker Labs,,http://www.wavemakerlabs.com/,,,https://www.facebook.com/WaveMachineLabs,opportunities@wavemakerlabs.com,,,Singapore,,Live,1
,Wego.com,"one of the world’s most comprehensive travel metasearch engines. Wego compares and displays real-time flights, hotel pricing and availability from hundreds of leading travel sites from all around the world on one simple screen.",Wego.com,,@wego,https://www.facebook.com/wego,masri@wego.com,,,Singapore,,Live,1
,Yuanta Venture Capital,"nvests in innovative technology businesses, not only providing the necessary capital, but also assisting by providing management consulting services. Yuanta Venture Capital also works in conjunction with the overall strategy of its parent financial holding company in providing investment banking services, assisting both companies in their growth. ",http://www.yuanta.com/English/AboutYuanta/A09/T001_A060400.aspx,,,,,2002,,Taiwan,,Live,1
,Yuuzoo,,http://www.yuuzoo.com/,,@YuuZooNow,https://www.facebook.com/pages/YuuZoocom/10828081666,info@yuuzoo.com,,,Singapore,,Live,1
,East Ventures,,http://east.vc/alpha/,,@eastventures,,,,,Indonesia,,Live,1
,Elasitas Technologies Limited,A reputable and leading enterprise providing customizable platforms and integrated solutions in the industry of telecommunications and information.,http://www.elasitas.com/,http://www.elasitas.com/blog/,,,,,,Indonesia,,Live,1
,Gemalto,,http://www.gemalto.com/,,@Gemalto,https://www.facebook.com/gemalto,,,,,,Live,1
,Fold7,,http://www.fold7.com/,http://www.fold7.com/news,@Fold7,,hello@fold7.com,,,UK,,Live,1
,BeePlex,,http://www.beeplex.org/,,,,rseidlein@gmail.com,,,Singapore,,Live,1
,Pacific Place,,http://www.pacificplace.com.hk/en/,,,,ppshopping@swireproperties.com,,,Hong Kong,,Live,1
,Mercatus Capital,"an Asia-Pacific Angel Investment fund, with focus on Technology, HealthCare, Biomedical, CleanTech,Material Sciences and Retail",http://mercatus-capital.com/,,@Mercatuscapital,https://www.facebook.com/pages/Mercatus-Capital/180174898684455,,,,Singapore,,Live,1
,Zalora,"Fashion's latest destination. Shop over 600+ brands and 30,000 products with FREE nationwide delivery, 30-days return and Cash On Delivery.",http://www.zalora.com.my/,http://blog.zalora.com.my/,@ZaloraMalaysia,https://www.facebook.com/ZaloraMalaysia,customer@zalora.com.my,,,Malaysia,,Live,1
,Mediatek,"s a leading fabless semiconductor company for wireless communications and digital multimedia solutions. The company is a market leader and pioneer in cutting-edge SOC system solutions for wireless communications, high-definition TV, optical storage, DVD and ",http://www.mediatek.com/en/index.php,,,https://www.facebook.com/pages/%E8%81%AF%E7%99%BC%E7%A7%91%E6%8A%80-MediaTek/238609946158320,,1997,,Singapore,,Live,1
,Netccentric Pte Ltd,,http://www.netccentric.com/,,@Nuffnang_2,https://www.facebook.com/pages/Netccentric-Pte-Ltd/242838362425804,,2006,,Singapore,,Live,1
,Starhub,,http://www.starhub.com/,,@StarHub,https://www.facebook.com/StarHub,,2000,,Singapore,,Live,1
,WholeTree Ventures,,http://www.wholetree.com/corpinfo.html,,,,au_info@wholetree.com,2002,,Singapore,,Live,1
,International SOS,"the world’s leading international healthcare, medical assistance, and security services company.",http://www.internationalsos.com/en/,,@IntlSOS,https://www.facebook.com/InternationalSOS,,1985,,USA,,Live,1
,TCP Capital,"n externally-managed specialty finance company focused on middle-market lending. We have elected to be regulated as a business development company, or BDC, under the Investment Company Act of 1940. Our stock is traded on NASDAQ under the ticker symbol ""TCPC"".",http://www.tcpcapital.com/,,,,investor.relations@tcpcapital.com,,,USA,,Live,1
,Pasco,,http://www.pasco.com/,,@pascoscientific,https://www.facebook.com/pasco.scientific,,,,USA,,Live,1
,Yushan Ventures,"invests time and money to further, promote, and assist globally focused mobile start-ups from their infancy stage to maturity in their efforts to build, scale, and expand successful products faster and smarter by providing seed level direct investment and connections to additional funding sources, industry expertise, and international relationships.",http://yushanventures.com/,,,https://www.facebook.com/YushanVentures,info@yushanventures.com,,,Taiwan,,Live,1
,Virtuous Investment,A non-profit organisation passionate about creating a vibrant ecosystem for angel investing in Malaysia.,http://www.vic.org.my/,,@vic_my,https://www.facebook.com/VirtuousInvestment,,,,Malaysia,,Live,1
,Battleventures,,http://www.battleventures.com/,,@jpaine,,,,,,,Live,1
,Emirates Competitiveness Council,a UAE federal government organization that serves as a conduit between the public and private sectors to strengthen the UAE’s competitiveness by actively informing policy creation and process development of federal and local government bodies to become more globally competitive.,http://www.ecc.ae/,,,,info@ecc.ae,,,Thailand,,Live,1
,Research in Motion,"a global leader in wireless innovation, revolutionized the mobile industry with the introduction of the BlackBerry® solution in 1999.",http://www.rim.com/,http://blogs.blackberry.com/,@BlackBerry,https://www.facebook.com/BlackBerry,help@rim.com,,,USA,,Live,1
,Etisalat,s the Middle East’s largest operator and the GCC’s third largest corporation. With a market value of approximately Dhs. 80 billion (USD 20 billion) and annual revenues of over Dhs. 32 billion (USD 8.7 billion) Etisalat is today on the verge of being numbered amongst the top ten operators in the world. ,http://www.etisalat.com/,,@EtisalatUAE,https://www.facebook.com/Etisalat,,,,UAE,,Live,1
,IEEE,Fostering technological innovation and excellence for the benefit of humanity. ,http://www.ieee.org/index.html,,@IEEEorg,https://www.facebook.com/IEEE.org,,,,China,,Live,1
,Clearpoint,,http://www.clearpointventures.com/,,,info@clearpointventures.com,,,,USA,,Live,1
,Aviva Investors, a global asset management business dedicated to building and providing our clients with focused investment solutions.,http://www.avivainvestors.com/,,,,info.sg@avivainvestors.com,,,Singapore,,Live,1
,GroupM,"the world's leading media investment management operation. It serves as the parent company to WPP media agencies Maxus, MEC, MediaCom, & Mindshare.",http://www.groupm.com/,,@GroupMWorldwide,https://www.facebook.com/pages/GroupM/253830354652444,,,,USA,,Live,1
,MTS,,http://www.mts.com/,,,, info@mts.com ,,,USA,,Live,1
,Intel Corporation,,http://www.intc.com/,http://blogs.intel.com/,@INTC_PR,https://www.facebook.com/Intel?rf=109409872410929,,1968,,USA,,Live,1
,DMGT,"Empowering people through information since brothers Alfred and Harold Harmsworth established the Daily Mail in 1896, DMGT is a publicly listed company quoted on the London Stock Exchange",http://www.dmgt.co.uk/,,@DMGTplc,,,,,,,Live,1
,Orange ftgroup,,http://www.orange.com/en/home,http://live.orange.com/en,@orange,,,,,UK,,Live,1
,Sandbox Industries,,http://www.sandboxindustries.com/,,@SandboxInd,https://www.facebook.com/SandboxIndustries,,,,USA,,Live,1
,KlickVentures,supports companies in the market introduction of their products with a broad spectrum of services.,http://www.klickventures.com/,,,,info@klickventures.com,,,Germany,,Live,1
,Daiwa Capital,,http://www.daiwacapital.com/,,@DaiwaCapital,,,,,Japan,,Live,1
,Adways,,http://adways.net/en/,,@Adways_Ventures,https://www.facebook.com/adwayscorp,,2001,,Japan,,Live,1
,Gilkor,"the information portal promos, discounts, online communities, forums and mobile applications in Indonesia about credit card specifically designed to help us look for promo-promo information that can be enjoyed from the credit card we have.",http://gilkor.com/,,@GILKOR,https://www.facebook.com/gilkor.ind,,,,Indonesia,,Live,1
,Cradle,"an agency under the Ministry of Finance, Malaysia (MOF) is a not-for-profit organisation that manages the RM100 million Cradle Investment Programme since its inception in 2003. An additional RM50 million was recently added to this allocation under the 10th Malaysian Plan for 2011 and 2012.",http://www.cradle.com.my/,,,,enquiries@cradle.com.my,,,Malaysia,,Live,1
,Tandemic,,http://tandemic.com/,,@tandemic,,speakwithus@tandemic.com,,,Malaysia,,Live,1
,NUS Enterprise,provides an entrepreneurial and innovative dimension to the University's core research and educational activities.,http://www.nus.edu.sg/enterprise/,,,https://www.facebook.com/pages/NUS-Enterprise/202865196395036,enterprise@nus.edu.sg,,,Singapore,,Live,1
,Seraph Group,,http://www.seraphgroup.net/,,@SeraphGroup,,ty@seraphgroup.net,2005,,,,Live,1
,Travel Capitalist,,http://www.travelcapitalist.com/,,@tcapitalist,https://www.facebook.com/pages/Travel-Capitalist-Ventures/111490872234568,funding@travelcapitalist.com ,,,USA,,Live,1
,Innovation Works,"plays a vital role in Southwestern PA's technology economy. We invest capital, business expertise and other resources into high-potential companies with the greatest likelihood for regional economic impact.",http://www.innovationworks.org/,,@iwpgh,https://www.facebook.com/iwpgh,,1999,,USA,,Live,1
,Temasek Holdings,,http://www.temasek.com.sg/,,@TemasekHoldings,https://www.facebook.com/pages/Temasek-Holdings/205314572816271,enquiry@temasek.com.sg,1974,,Singapore,,Live,1
,Netprice.com,,http://www.netprice.com/english/index.html,,,,ir@netprice.com,1999,,Japan,,Live,1
,Founders Fund,,http://www.foundersfund.com/,,@foundersfund,https://www.facebook.com/pages/The-Founders-Fund-Inc/123399677101,,,,USA,,Live,1
,Sherpalo Ventures,,http://www.sherpalo.com/,,,,info@sherpalo.com,,,USA,,Live,1
,Get2Volume Accelerator," focuses on innovative semiconductor and microelectronics emerging growth companies. Successful semiconductor and microelectronics companies are global from day one. Get2Volume brings global capabilities, capital and connections to enable emerging growth company success.",http://www.g2vaccelerator.com/,,,,info@g2vaccelerator.com,,,Singapore,,Live,1
,Barclays Capital,,http://www.barcap.com/,,@barclayscapital,,,,,Singapore,,Live,1
,KPMG Corporate Finance,,http://www.kpmgcorporatefinance.com/,,,,pisom@kpmg.com,,,USA,,Live,1