<?php
header("Content-Type: application/force-download");
header('Content-Disposition: attachment; filename=people_sample_old.csv');
?>Headers :,Name,Blog,Twitter,Linkedin,Profile Image,Description,Companies,Investment Organizations,Email,Active? 
Data Format:,[First Last name],"[Blog URL],[Blog Feed URL]","[Twitter handler],[Twitter handler2]",[URL],,[Text description],,,[Email address],"[""1""/""0""]"
1,Pierre Hennes ,,@pierrehennes,http://www.linkedin.com/pub/pierre-hennes/7/483/9b8,,"Pierre has significant experience in Venture Capital and has been active in new venture creation across Asia since 2003. He is currently the Managing Partner of Extream Ventures (www.extreamventures.com), an early-stage venture fund based in Singapore, funded in part by the Singapore National Research Foundation. In addition to his role at Extream Ventures, he is a Partner of Upstream Ventures (www.upstreamventures.com), a Singapore-based seed & start-up investment firm launched in 2003.",,,,1
2,Mahim Chellappa,,,http://www.linkedin.com/pub/mahim-chellappa/6/a45/849,,"Mahim manages the Funds’ non-China investments, providing leadership and support in a variety of functions, including global business development (including within the U.S. and Europe), finance and administration, operations, and marketing. Mahim also helps source and originate new investments and structure exits.",,,,1
3,Chris Evdemon,,@evdemon,http://www.linkedin.com/in/evdemon,,"Chris has 12 years of “hands on” entrepreneurial and angel investments experience, primarily in IT, as well as in the education and entertainment industries. ",,,,1
4,William Klippgen,,@klippgen,http://www.linkedin.com/in/alwaysinnovate,,William has been active in the online space since 1995 and had a stint as a core technology engineer with Excite Inc. in Mountain View. Excite was the world's largest internet search engine and used many of the technologies later adopted by Google,,,,1
5,Kyota Itoi,,,http://www.linkedin.com/pub/kyota-itoi/1a/394/607,,"Kyota Itoi has twelve years of senior sales management experience in the IT industry. His industry experience covers wireless and wired networking and telecommunications equipment and software sales for   Allied Telesis, Lucent Technologies, and Top Layer Networks Japan. His customers and partners have included IBM, CTC, Sumisho, Netmarks, NTT, NTT DoCoMo, KDDI, NTT Data, Matsushita, and Sharp, among others. Mr. Itoi has been involved in sales and marketing of LAN switches, voice systems, PBX CTI application software, wireless LAN systems, Routers, Hubs, ATM Switches, Intrusion Prevention Systems, and wireless technologies. Mr. Itoi also held project management and sales positions in the commercial real estate industry earlier in his career. He is a graduate from Keio University",,,afushida@japanvp.com,1
6,Wong Poh Kam,connect-the-dots-Singapore.blogspot.com,@pohkam,http://www.linkedin.com/in/pohkam,,"Wong Poh Kam is concurrently a Professor at the School of Business, as well as Director for NUS Entrepreneurship Centre. He has published in numerous international refereed journals on innovation policy, industrial and competitiveness policy and technology entrepreneurship, and has also consulted widely for international agencies such as the World Bank and Asian Development Bank, various government agencies in Singapore such as A*STAR, EDB and IDA, and many high tech firms in Asia.",,,william.klippgen@bafspectrum.com,1
7,Eugene Wong,,,http://www.linkedin.com/pub/eugene-wong/0/118/881,,,,,,1
8,Andy Bottomley,,,,,,,,,1
9,Tan Kim Seng,,,http://www.linkedin.com/pub/kim-seng-tan/0/160/aa4,,He brings with him 19 years of venture capital management and banking experience in addition to 5 years of operating experience within the IT and electronics industries. He is the Chairman of Industry Development Committee of the Singapore Venture Capital & Private Equity Association and has previously served as the Treasurer.,,,,1
10,Yishai Klein ,,,http://www.linkedin.com/pub/yishai-klein/0/35/b1,,"Yishai joined Giza in 1997 and relocated to Singapore in 2001 to open and head Giza's Asia office. He has overseen the Fund's direct investment and portfolio business development activities in the region. In the past 18 months, he has led investments in four regionally based companies in the clean-tech and communications sectors. He has advised portfolio companies, such as: Altair, Lucid, IntelliDx, Actimize, Envara and Cyota, with their expansion into the region.",,,yklein@gizavc.com,1
11,Carmelo Pistorio,,,http://www.linkedin.com/pub/carmelo-pistorio/0/a1/2ba,,"has over 10 years of international entrepreneurial experience across multiple high-tech industries including software, semiconductors, and environmental systems and solutions. His operational experience spans all aspects of a startup, and he has held positions ranging from founder and investor to senior executive for operations, as well as serving on the boards of a number of companies across Europe and Asia.",,,,1
12,Andreas Kröll,,,http://www.linkedin.com/pub/andreas-kroell/11/968/24b,,"Andreas has been responsible for the international operations of the company, in particular the investments in the US. He lead the Nanostart investments in Lumiphore, BioMicro and NanoGram (US) and was also involved in the MagForce, Holmenkol and Namos (Germany) transactions. Andreas has been representing Nanostart on the boards of Lumiphore and BioMicro (US), and has also been managing the other portfolio holdings of Nanostart in the US, including NanoGram and Nanosys. He brings in a broad know-how and network in nanotechnology and its key industries such as cleantech or medicine/life sciences. His professional experience is based on a career in corporate finance, including his role as a team and project leader for major international investment banks and corporate finance firms such as Deutsche Bank and Deloitte & Touche, where he was involved in a large number of M&A- and equity transaction",,,,1
13,Damien Lim,,,http://www.linkedin.com/pub/damien-lim/0/aa/966,,He has 20 years experience in private equity and investment banking,,,,1
14,Mark S. Hauser,,,,,"He oversees Tamarix Capital’s international private equity effort. Prior to joining Tamarix, he was a Senior Managing Director at Sandell Asset Management, an international multi-strategy alternative asset manager, where he founded and was global head of the firm's private equity practice as well as a member of the investment committee.  Prior to joining Sandell, he was a Managing Director at FdG Associates, a New York-based middle- market private equity fund focused on investing in family owned businesses. Prior thereto he was the founder and Managing Director of Tamarix Capital Corporation, a New York-based investment and merchant banking company that made investments in businesses with significant growth potential. Mark has served as an officer and on the boards of directors of various portfolio companies. Before founding Tamarix, he was a Managing Director at Ocean Capital Corporation, a private international investment banking firm. Mark began his career as a corporate attorney, practicing in New York, Sydney and London. He holds a Bachelor of Economics Degree and a Bachelor of Law Degree from Sydney University and a Master of Law Degree from the London School of Economics & Political Science.",,,,1
15,Douglas Abrams,http://douglasabrams.com/,,http://www.linkedin.com/in/douglasabrams,,"Prior to coming to Singapore, he managed information technology at J.P.Morgan for 14 years. From 1997 to 1999, he was Global Markets Head of Internet Marketing, and from 1991 to 1997, he was VP and Manager of Investment Banking Technology.  Before working on Wall Street, he began his career in 1980 on the editorial side of Crown Publishers, where he was an acquisitions editor until 1986.",,,,1
16,Tan Lip-Bu,,,,,"One of the top venture capitalists bridging Asia and Silicon Valley, Tan founded Walden International in 1987. Today, the San Francisco-based Walden is a $1.9 billion VC fund that has invested in companies such as Chinese-language portal Sina.com (SINA). Tan, who has a master's degree in nuclear engineering from MIT and an MBA from the University of San Francisco, is on the board of Sina as well as Flextronics and Semiconductor Manufacturing International Corp.",,,,1
17,Vinnie Lauria,,@vlauria,http://www.linkedin.com/in/vincentlauria,,,,,,1
18,Amit Anand,,@amitvedanand,http://www.linkedin.com/pub/amit-anand/3/290/6b7,,"has over 14 years of active career in go-to-market strategies and corporate development for start-ups and corporations alike. Management, Leadership positions at Progress Software, Fiorano Software and Tata Infotech. Also started and concluded a trade sale of an animation and gaming business, ettaminA studios in India",,,amit@jungle-ventures.com,1
19,Jackie Lee,,@clickTRUE,http://www.linkedin.com/in/jackieleechoonyau,,"He was the CEO and Founder of HardwareZone since 1998. During his term, he has founded HardwareZone.com which is the No.1 Technology portal in Southeast Asia and HWM (HardwareMAG.com) which is a Leading Technology Monthly magazine. HWM now publish 5 editions in Singapore, Malaysia, Thailand, Indonesia, Philippines. HWZ also publishes GameAxis.com and GameAxis China and GameAxis Unwired Magazine and PVi (Photo/Video magazine).",,,,1
20, Michiel Adriaan Wind,,,http://www.linkedin.com/pub/michiel-wind/47/708/68,,,,,,1
21,Tay Koon Chuan,,,http://www.linkedin.com/pub/koon-chuan-tay/1/250/831,,"He is also a director of VChain Corporation Ltd, i-Pacific Office Pte Ltd and OneCapital Asia Fund I Ltd. Prior to joining Fortune Venture Management Pte Ltd in September 2005, he was the CEO of Magzone Asia Pte Ltd and VChain Corporation Ltd. Mr Tay graduated from the National University of Singapore with a First Class Honours in Mechanical Engineering, and holds a Master of Science degree in Computer Science from the University of Wisconsin, as well as a Master of Business Administration degree in Banking and Finance from the Nanyang Technological University of Singapore.",,,"kctay@vcfortune.com, lpsoh@vcfortune.com",1
22,Philip Yeo,,,http://www.linkedin.com/pub/philip-yeo/33/b62/997,,"He was Special Advisor for Economic Development (Prime Minister's Office) from April 2007 to August 2011 and Senior Advisor for Science and Technology in the Ministry of Trade and Industry from April 2007 to September 2008. As Special Advisor for Economic Development in the Prime Minister's Office, Mr. Yeo assisted the Prime Minister's Office in establishing new economic links with foreign governments who value Singapore's development experience, and provided strategic inputs to establishing strategic partnerships and opening up opportunities with other fast growing economies.",,,,1
23,"   

John F. Eckert",,,http://www.linkedin.com/pub/john-eckert/12/804/752,,"Prior to founding McLean Watson Capital, John and Loudon Owen financed and advised Softimage, a world leader in high-end 3D animation, in its growth from 4 to 250 employees, its IPO on Nasdaq in 1992 and the sale to Microsoft in 1994. John and Loudon served as the Joint COO for Softimage from 1993 to its sale. John has extensive experience in corporate finance, having served as a VP and Director in Corporate Finance and Capital Markets of Wood Gundy Inc. and CIBC Wood Gundy in Canada. He also served as Managing Director of CIBC Wood Gundy (Australia), a merchant bank",,,,1
24,Peter Tan,,,http://www.linkedin.com/pub/peter-tan/0/b2/20b,,"Peter co-founded the SkyVen Group in 2000. Prior to that, Peter held various senior marketing, product development, alliance development and operations consulting roles at MasterCard International including Director of Corporate Products, Asia Pacific Region and Director of Alliance Development. Earlier, he was a Corporate and Retail Banker with DBS Bank and a corporate lawyer at M/s Shook Lin & Bok focusing on venture capital, private placements, fund management, banking, securities regulation, corporate finance and mergers and acquisitions. As a corporate lawyer, he has advised many venture capital companies, banks and asset management houses on numerous transactions and has structured a variety of investment and fund raising vehicles for them including venture capital funds, initial public offerings, syndicated loans, note issues, joint ventures and unit trusts.",,,,1
25,Hideyuki Katsuchi,,,,,"Mr. Hideyuki Katsuchi was born in 1970 in Japan. He has B.A. degree from Keio University in Japan in 1994 and MBA degree from University of Chicago in 2001. Before joining SBI Holdings, he worked for corporate finance and investment in Resona Bank and Mitsubishi UJF Securities.     Mr. Katsuchi joined SBI Holdings in 2005. He has been working mainly for overseas investment as well as business development. After the position of a director for SBI Ven Capital, Singapore subsidiary of SBI and a head office of SBI in ASEAN region, he is currently a deputy general manager of overseas business promotion department of SBI Holdings.",,,,1
26,Chua Kee Lock ,,,http://www.linkedin.com/pub/kee-lock-chua/0/119/663,,"Graduated with a Bachelor of Science degree in Mechanical Engineering from the University of Wisconsin at Madison, and a Master of Science from Stanford University under NatSteel’s scholarship.",,,,1
27,Dr Finian Tan,,,http://www.linkedin.com/pub/dr-finian-tan/0/338/629,,"As head of the Asia Pacific operations, Dr. Tan created and built the Asian operations of the Draper Fisher Jurvetson ePlanet Ventures Fund. In 2002, Dr. Tan reduced his role at DFJ ePlanet and concurrently assumed the position of Managing Director and head of the Credit Suisse First Boston group of banks (""CSFB"") in Singapore. During his tenure as head of the CSFB group of banks in Singapore, Dr. Tan remained as chairman of DFJ ePlanet's Asian Investment Committee and to-date remains a member of the board of DFJ Eplanet (S) Ltd in Singapore. Prior to that, he served in the Singapore Government as Deputy Secretary of the Ministry of Trade and Industry and later as Deputy Chairman of the National Science and Technology Board and Co-chairman of the US$1 billion TIF fund.",,,,1
28,Wai Kit Lau,,,http://www.linkedin.com/pub/wai-kit-lau/4/31/684,,"He has over fourteen years of management, investment and mergers and acquisitions experience in Asia, and previously he joined WI Harper Group (""WIH"") in 2001 as Managing Director with an extensive track record in the TMT industries. In 1999, Wai Kit led a consortium of investors in acquiring a minority stake in PT Satelit Palapa Indonesia. PT Satelit Palapa Indonesia was the owner of one of the two satellites of Indonesia and the third largest mobile carrier in Indonesia. Within two years, he successfully concluded a profitable sale of the investment to IndoSat.",,,waikit@gobivc.com,1
29,Osamu Hosokubo,,,http://www.linkedin.com/pub/osamu-hosokubo/0/b49/92,,"is the President at Japan Asia Investment Co. Ltd. He was formerly the Managing Director of the firm since 2007 and served as its Director and Human Resources Group Officer. Mr. Hosokubo serves as Chief Executive Officer of Japan Asia Investment (China) Co.,Ltd. Mr. Hosokubo served as Head of the Global Investment department ofJapan Asia Investment Co. Ltd. He served as the President of JAIC Asia Capital Pte. Ltd. Mr. Hosokubo serves as Director and formerly the Representative Director at JAIC Seed Capital Co., Ltd. He has over ten years experience in venture capitalism, most of which are in Asia. Mr. Hosokubo serves as Vice President and Director at JABOC Ltd. He is a Director at Japan Asia Investment Co., Ltd. Mr. Hosokubo holds a degree from Keio University.",,,ir@jaic-vc.co.jp.,1
30,Hiroshi Yamada,,,http://www.linkedin.com/pub/hiroshi-yamada/0/b5/889,,"He serves as President and Chief Executive Officer at JAFCO American Ventures Inc. Mr. Yamada serves as the President, Chief Executive Officer, and Member of the Investment Committee at JAFCO Investment (Asia Pacific) Ltd. He has been a Member of Investment Committee since 2001. Mr. Yamada has more than 25 years experience in venture capital and related industries. He started his professional career at Nomura Securities Co., Ltd. in 1978 immediately after his graduation. After having worked for the company’s domestic branch office and completed the company’s scholarship program and also having worked in various assignments both in Japan and overseas, Mr. Yamada became a Securities Analyst and Strategist in 1983 at Institutional Research and Advisory Department which exclusively served overseas institutional investors investing in Japanese public equity market. He worked at the department for six years until 1989. ",,,,1
31,Seah Kian Wee ,,,http://www.linkedin.com/pub/kian-wee-seah/0/b2b/b80,,"has over 13 years of experience in Venture Capital/Private Equity fund management and he joined UOBVM in 1997. As Managing Director, he is responsible for the overall profit and loss, fund administration, investment and divestment. Kian Wee currently chairs the investment committee of several UOB-sponsored regional private equity and venture capital funds. He has served on the board and Audit/Compensation/Nominating committees of public listed companies such as Wuxi Pharmatech, China Precision Technology and Sunvic Chemical among others.",,,,1
32,Dr. Hong Chen,,,http://www.linkedin.com/pub/hong-chen/0/96/598,,"Before starting The Hina Group, Dr. Chen founded and served as the Chairman and CEO of GRIC Communications, and led its successful IPO on NASDAQ in 1999. Dr. Chen served GRIC's CEO from 1994 to early 2003 and continues to serve as the Chairman of GRIC, a global leader in deploying world’s largest virtual dial up and broadband WiFi network in 150 countries. Prior to GRIC, he founded and was president and CEO of Aimnet, a successful Northern California Internet service provider that was acquired by Verio in 1997, which was sold to NTT in 2000 for $5.6B.",,,,1
33,Teo Ming Kian,,,,,,,,cfo@pierceandpierce.com,1
34,Lee Boon Yang,,,,,"He has extensive experience in public service.  He served as the Member of Parliament for Jalan Besar and Jalan Besar GRC from December 1984 to April 2011.  He was the Minister for Information, Communications and the Arts before retiring from political office in March 2009.",,,,1
35,Lauren Liang,,,http://www.linkedin.com/in/laurenliang,,"Lauren builds on extensive experiences in Television and Media as a Retained Consultant for Strategy, Business Development and Planning at Technicolor, Executive Director at NBC Universal’s Peacock Equity Fund, Director, of Business Development at NBC Universal, and Director, Sales Strategy and Finance at NBC Universa",,,,1
36,Dr. Stephen Chiao,,,http://www.linkedin.com/pub/stephen-chiao-dr/0/190/a23,,,,,,1
37,Tan Bien Chuan,,,http://www.linkedin.com/pub/bien-chuan-tan/8/841/862,,"He has led OWW's investment in more than 30 unlisted companies in Singapore, Malaysia, Indonesia, Thailand, China and Hong Kong in the areas of IT, food, healthcare and consumer products. Bien Chuan is/has been a member of the boards of Asian Home Gourmet (acquired by Cerebos Pacific Ltd), Craft Print International, Showpla Hong Kong (acquired by Arrk Corp) and Goodpack.",,,tonnght@gmail.com,1
38,Andy Lim,,,http://www.linkedin.com/pub/andy-lim/11/53b/204,,"the founder and Chairman of private equity firm Tembusu Partners and the Chairman and substantial shareholder of a publicly listed company Viking Offshore & Marine Ltd. He is also the Executive Director of Associated Leisure International, a family holding company and Chairman of MoneyWorld Group of Companies, a leading foreign exchange player with offices in China, Hong Kong, Singapore and New Zealand.",,,,1
39,Peter Chan ,,,,,"Peter set up Baring Communications Equity Asia (""BCEA"") for the ING Group in 1996 as the first specialized regional media and communication fund under the combined sponsorship of the ING Group and the EDB. He was responsible for the general management and investment/divestment strategy of the fund as well as investor relations. Peter led the spin out of the BCEA team into Crest Capital as an independent regional private equity practice. Since then, he has initiated a number of funds which Crest Capital currently manages across the region. He had conceptualized The Enterprise Fund's unique financing model in 2005 and led its launch with IE Singapore's sponsorship in 2006.",,,peter.chan@crestcapitalasia.com,1
40,Priscilla Davies,,,http://www.linkedin.com/pub/priscilla-davies/26/52/741,,Priscilla has over 20 years experience in financial services having qualified as a chartered accountant.  Priscilla joined Henderson Group in 2000 in a senior tax role and moved across to Henderson’s private equity division in 2004 where she oversaw its finance and investment operations.,,,priscilla.davies@henderson.com,1
41,Sir John Peace,,,,,"Sir John has a strong financial services and retailing background.  In 1980 he was one of the founders of CCN Systems, an early pioneer of credit scoring techniques, risk models and the development of customer segmentation systems.  CCN also provided credit card processing services to financial and retail organisations.  CCN went on to become Experian plc, a global information services company providing data and analytical tools to clients in over 90 countries. ",,,be.secure@sc.com,1
,Darius Cheung,,@Rius,http://www.linkedin.com/pub/darius-cheung/0/3b7/47,,,,,darius.cheung@gmail.com,1
,Aileen Sim,,,http://www.linkedin.com/in/aileensim,,,,,aileensim@gmail.com,1
,Kenneth Karta,,,http://www.linkedin.com/in/kennethkarta,,,,,kenneth.karta@gmail.com,1
,Sion Karta,,,,,,,,sion.karta@gmail.com,1
,Alex Wong,,,,,,,,alex.cb.wong@gmail.com,1
,Fawaz Zui,,,http://www.linkedin.com/pub/fawaz-zu-bi/1/23b/87b,,,,,fzubi@acceleratortech.com,1
,Darcy Naunton,,@DarcyNaunton,http://www.linkedin.com/in/darcynaunton,,"Darcy was previously an Investment Analyst at Mercer Investment Consulting, a major institutional asset consultant, involved in providing portfolio construction and asset selection advice to large institutional investors including pension funds, insurance companies, fund-of-fund investment managers and endowments. He first began working in the financial services industry in 2004 as a paraplanner at a private financial planning firm in Western Australia.",,,darcy@adventurecapital.vc,1
,Madhu Avalur,,@avalur,http://www.linkedin.com/in/avalur,,"Serial entrepreneur, experienced in the strategic planning, development and management of international business operations with specific expertise in online media and entertainment. Has extensive experience assembling core teams, leading people, implementing and overseeing technology programs. Possess an in-depth understanding of emerging technologies and their commercial applications. Consistently successful in analyzing market trends and capitalizing on global market opportunities to create high-profit, high-visibility partnerships through product development, brand positioning, and innovative marketing media solutions. Culturally sensitive and internationally travelled leader.",,,avalur@angaros.com,1
,Adrian Stone,,,http://www.linkedin.com/in/adrianstone,,,,,adrian@angelcube.com,1
,Raiyo Nariman,,,http://www.linkedin.com/in/raiyo,,"Raiyo’s career has included roles and projects across all sectors, from start-ups to government ministries, the corporate world to through to academia and non-profit sector. He has worked in most industries from technology and IP commercialisation and new ventures, through to academia and management consulting, technology (both high and low) to professional services. ",,,raiyo@angelsden.com,1
,Adrian Vanzyl,,@adrianvanzyl,http://www.linkedin.com/in/adrianvanzyl,,,,,adrian@ardentcap.com,1
,Takeshi Ebihara,,@TakeshiEbihara,http://www.linkedin.com/in/ebihara,,,,,ebihara@batavia-incubator.com,1
,Zia Zaman,,@zzaman,,,,,,zz@beaverlakecapital.com,1
,Paul Deng,,,http://www.linkedin.com/pub/paul-deng/8/910/271,,"8 years product experience with solid knowledge on Consumer Electrics, Digital Imaging & Information Technology products. Good connection with top OEM/ODM suppliers based in Mainland China, Hongkong, Taiwan, Singapore, as well as the rest of the world. Close relationship with major solution/chipset providers, panel makers, cloud-based service platforms, and design houses. Familiar with the product requirements and regulations of major international markets like USA, Canada, EU, Japan, China, and Mexico. Deep insights on retail operation. ",,,climber1978@gmail.com,1
,Pierre Hennes ,,@pierrehennes,http://www.linkedin.com/pub/pierre-hennes/7/483/9b8,,,,,pierrehennes@extreamventures.com,1
,Chow Yen Lu,,,http://www.linkedin.com/pub/yen-lu-chow/0/164/6b4,,,,,yenluc@wholetree.com,1
,Teh Shi Hua,,,http://www.linkedin.com/profile/view?id=14002036&authType=NAME_SEARCH&authToken=WJtb&locale=en_US&srchid=9fda6fe1-ec66-40eb-88d5-56bf0ab6e6a5-0&srchindex=1&srchtotal=1&goback=%2Efps_PBCK_teh+shi+hua_*1_*1_*1_*1_*1_*1_*2_*1_Y_*1_*1_*1_false_1_R_*1_*51_*1_*51_true_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&pvs=ps&trk=pp_profile_photo_link,,,,,shihua@capvista.com.sg,1
,Gaetan Japy,,@gaetanj,http://www.linkedin.com/pub/ga%C3%ABtan-japy/0/a8/6b8,,,,,gaetan@japy.net,1
,Basil Darwish,,@badarwish,http://www.linkedin.com/in/basildarwish,,,,,basil.darwish@citi.com,1
,Steven Fang,,,http://www.linkedin.com/pub/steven-fang/12/a3b/251,,"With a deep passion for new ventures and life's adventures, he is constantly seeking and learning from his network of friends and associates.",,,stevenfbs@gmail.com,1
,Michiel Wind,,,http://www.linkedin.com/pub/michiel-wind/47/708/68,,,,,ma.wind@ch-investments.com.sg,1
,Dzung Nguyen Manh,http://ameblo.jp/nguyen-dung-nemureshi2,@nemureshi2,http://www.linkedin.com/in/nguyenmanhdung,,,,,dung@cyberagentventures.com,1
,Akihisa Fujita,,@akihisafujita,http://www.linkedin.com/in/akihisafujita,,"Fujita who was doing work of the Internet from 1994 was engaged in establishment of the first Internet ad special company ""cyber communications"" (cci) in Japan in 1996, and led to the success as a COO till 1999, towed the annual turnover of cci to 40 million dollars.",,,fujitad2c@gmail.com,1
,Linh Thai,,@linhdini,http://www.linkedin.com/in/linhvthai,,,,,linh.thai@vinacapital.com,1
,Dmitry Levit,,@Dimalevit,http://www.linkedin.com/in/levit,,"He focus on developing digital media businesses in early stage emerging markets, with particular focus on Southeast Asia (Singapore, Malaysia, Indonesia, Vietnam, Thailand and the Philippines).",,,dmitry@digitalmedia.vc,1
,Mark Suckling,,,http://www.linkedin.com/in/marksuckling,,"11 years working in the online media sector. Strong expertise covering both strategy and operational roles. Previous employment includes consulting projects in private, public and not-for-profit sector. Also extensive digital product management and development experience for global media website and a number of online start-ups. A digital expert with extensive knowledge of developing successful online products.",,,mark@digitalmedia.vc,1
,Lee Buckerfield,,@leebuckerfield,http://www.linkedin.com/in/leebuckerfield,,"He has an extensive background in Online Media, Marketing & Advertising. Takes commercial and pragmatic approach to building solid finance teams to support high growth & constant change.",,,lee@digitalmedia.vc,1
,Rodrigo Martinez,,,http://www.linkedin.com/in/rodmart,,Internet pioneer in Brazil. Created several companies including two of the most acclaimed and successful: STI Internet and hpG.,,,rmartinez@dikaios.ch,1
,Jackson Chan,,,http://www.linkedin.com/in/jacksonchan,,"Prior to his current work, he was also a founder of an Internet E-commerce Business and a Mobile Telecommunication Start-up in Hong Kong. He has solid industry experience in Internet and technology sector",,,jackson.chan@dmgt.com,1
,Johannes De Back,,,http://www.linkedin.com/pub/johannes-de-back/45/910/256,,"Over 12 years international entrepreneurial experience across multiple high-tech industries including mobile, gaming, online and social. My operational experience spans all stages of a start-up: I held positions ranging from founder and investor to senior executive for operations. Created global businesses and took companies from an early stage to IPO or ‘exit’. Currently I am investing in start-ups and early-stage technology oriented companies with strong disruptive elements including Mobile, Gaming, E-commerce, Social Media companies. I am a builder by nature with a strong hands-on mentality. ",,,hans@dutchman-capital.com,1
,Nithipong Durongwattana,,@Duoearth,http://www.linkedin.com/pub/nithipong-durongwattana/31/b86/54a,,,,,nithmatabnr32@hotmail.com,1
,Piers Bennett,,@piersbennett,http://www.linkedin.com/in/piersbennett,,"Senior management experience of company start-up, implementation and rollout, plus re-structuring. Technical experience in Internet, Media and Telecommunications services. Professional skills covers financial and operational management, project management, investment appraisal and decision-making, data analysis and company acquisitions.",,,piers@ardentcap.com,1
,Lau Kin Wai,,,,,,,,lau@fatfishlab.com,1
,Kelvin Ong,,,http://www.linkedin.com/in/ongkelvin,,,,,Kelvinong@focustech.com.sg,1
,Sharon Seet,,@Sharonprincess,http://www.linkedin.com/pub/sharon-seet/22/405/587,,,,,seet.sharon@gmail.com,1
,Fuxin Jiao-Kiuru,,,http://www.linkedin.com/in/fuxin,,,,,fuxin@x2ventures.com,1
,Abhilash Tripathi,,,http://www.linkedin.com/in/abhilashtripathi,,,,,abhilash@gitpx.com,1
,Fang Soong Chou ,,@choufs,http://www.linkedin.com/pub/fang-soong-chou/0/11b/9b8,,"He has over 30 years of Technology, Management and Start-up experiences. He is best known for his pioneering work with Gemplus (now known as Gemalto), a world leader in smart card & secured transactions. He started their Asia operation in Singapore in 1989 when the market for smart card was non-existent. He was instrumental in Gemplus’ phenomenal growth in Asia to become the market leader and innovator, and grew the business from a start-up to an established Multi-National operations with major sales, R&D and manufacturing facilities throughout the region. He was presented with the medal for “Chevalier de l’Ordre National du Merite’’ from the French Government on 27 July 2005 for his contribution and promotion of Smart Card Technologies in Singapore and the Asia Region. He was also recognised by the industry with the D'ucoty Business Leader of the Year 2005 award by Frost & Sullivan.",,,fangsoong@gitpx.com,1
,Nick Palevsky,,,,,,,,palevsky@rocketmail.com,1
,Yasuhiko Yurimoto,,,http://www.linkedin.com/pub/yasuhiko-yurimoto/3/985/90a,,,,,yurimoto@globalbrains.co.jp,1
,Janelle Bowditch,,,http://www.linkedin.com/pub/janelle-bowditch/26/565/561,,,,,janelle@globalbrains.co.jp,1
,Daisuke Nakagawa,,,,,,,,nakagawa@globalbrains.co.jp,1
,Takahiro Koiwa,,,http://www.linkedin.com/profile/view?id=136460922&authType=NAME_SEARCH&authToken=ypSH&locale=en_US&srchid=035f6b7a-1be4-4f79-966b-973418565378-0&srchindex=1&srchtotal=1&goback=%2Efps_PBCK_Takahiro+Koiwa+_*1_*1_*1_*1_*1_*1_*2_*1_Y_*1_*1_*1_false_1_R_*1_*51_*1_*51_true_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&pvs=ps&trk=pp_profile_photo_link,,,,,koiwa@globalbrains.co.jp,1
,Katsuyuki Hasegawa,,,http://www.linkedin.com/pub/katsuyuki-hasegawa/56/884/511,,,,,hasegawa@globalbrains.co.jp,1
,Teruhiro Arai,,,http://www.linkedin.com/pub/teruhiro-arai/2b/796/a00,,,,,teruhiro.arai@gmail.com,1
,Anand Govindaluri,,@anand_govi,http://www.linkedin.com/profile/view?id=95904&authType=OPENLINK&authToken=qwYG&locale=en_US&srchid=f04d7856-35e9-4c5c-8faf-dcfc8a7a9ca6-0&srchindex=1&srchtotal=1&goback=%2Efps_PBCK_Anand+Govindaluri+_*1_*1_*1_*1_*1_*1_*2_*1_Y_*1_*1_*1_false_1_R_*1_*51_*1_*51_true_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&pvs=ps&trk=pp_profile_photo_link,,"Experience in venture capital, growth capital, private equity investments, leverage /management buy-outs, secondary market transactions, in healthcare, pharmaceutica, infocomm, education and cleantech companies",,,Anand@govinholdings.com,1
,Jeffrey Paine,,@jpaine,http://www.linkedin.com/in/jeffreypaine,,,,,jeff@battleventures.com,1
,Justin Hall,,@JVinnyHall,http://www.linkedin.com/pub/justin-hall/a/874/53a,,,,,justin@goldengate.vc,1
,Marvin Liao,,,http://www.linkedin.com/pub/marvin-liao/0/5/630,,"An experienced client-facing senior executive in the media and technology space in both large and start up growth companies, having managing large multifunctional teams across multiple countries. He has P&L management experience and most recently responsible for 100% revenue growth while running a business unit and building new sales channels in EMEA & the Emerging Markets regions for the last ~4 years.",,,marvinliao@yahoo.com,1
,Yumiko Egawa,,,http://www.linkedin.com/pub/yumiko-egawa/41/a90/212/en,,,,,yumiko.egawa@gree.net,1
,Tatsuo Tsutsumi,,,http://www.linkedin.com/pub/tatsuo-tsutsumi/1a/84b/b32,,,,,tatsuo.tsutsumi@gree.net,1
,Marilou Sia-Quesang,,,,,,,,marilouquesang@gmail.com,1
,Temmy Setiawan,,,http://www.linkedin.com/in/temmystw,,"Technology Specialist with almost 10 years of experience, ranging from Data Networks, Firewall, Video Conference, Sytems (Windows & Linux), Monitoring Tools, IPTV to PABX.",,,temmystw@yahoo.com,1
,Michel Birnbaum,,@MiBirn7,http://www.linkedin.com/pub/michel-birnbaum/0/2ba/4bb,,"Grew up and lived in US for 26+years. Worked for GE military, qualif project engineer of Apache/Blackhawk powerplant. Former Dir Investment Banking Hambrecht&Quist Europe; led over 40 tech transactions, IPOs, M&A and Private Placements. CEO of listed VC firm in London for restructuration. Expert at the EU in Framework 6 Priority3 (nanotech, tech transfer..). Worked with Universities and R&D centers on innovation and tech transfer advisory and models. Important study completed for large UK university.Extensive VC and corporate relationships US, Europe and Asia.Interim management for VC companies and advisory. Member of Sophia Antipolis Venture Capital, IVCS, summit selection committe since inception (1998). Author of Venture wire 2003 European Life sciences report. UK full IMRO, French licence, Deutsche Borse licence and US series 7&63, GE advanced engineering program participant. Approach methodology is from a business/strategic standpoint rather than just financial engineering. Approaching each opportunity with fresh eyes is paramount. Substantial involvement in US and Asia.Roll up the sleeve philosophy otherwise no fun!",,,michel@iglobepartners.com,1
,Sneha Menon,,@snehamenon,http://www.linkedin.com/in/snehamenon,,,,,sneha@infocomminvestments.com,1
,Lynee Loh,,,http://www.linkedin.com/in/lynneloh,,,,,lynne.loh@infocomminvestments.com,1
,Stanley Teo,,,http://www.linkedin.com/in/stanleyteohh,,,,,stanley@infocomminvestments.com,1
,Kuo Yi Lim,,,http://www.linkedin.com/in/limky,,,,,kuoyi@infocomminvestments.com,1
,Pang Heng Soon,,,,,,,,hengsoon@infocomminvestments.com,1
,Scott Anthony,http://blogs.hbr.org/anthony/,@ScottDAnthony,http://www.linkedin.com/in/scottdanthony,, ,,,santhony@innosight.com,1
,Pete Bonee,,,http://www.linkedin.com/pub/pete-bonee/3/56/808,,"25 years of leadership and entrepreneurial experience in the networking and IT industries, and 3+ years of experience in early-stage venture investing.",,,pbonee@innosight.com,1
,Piyush Chaplot,http://www.piyushchaplot.com/,@piyushchaplot,http://www.linkedin.com/in/piyushchaplot,,,,,pchaplot@innosight.com,1
,Andrew Sandes,,@andrewsandes,http://www.linkedin.com/in/andrewsandes,,"Dynamic, high energy, entrepreneurial leader with 14 years sales, marketing and corporate development experience across the Asia Pacific region. Proven track record of growing new business operations in Asia from standing start to multi-million dollar sales. Long term experience and understanding of markets, customers and cultures across Australia/NZ, South East Asia, North Asia (Japan, Korea, Taiwan and Hong Kong). Passionate about meeting new people, helping start new businesses, opening new markets and establishing new partnerships. Excellent understanding of technology products, solutions, markets and applications combined with a strong ability to rapidly build trusted relationships and deliver immediate results.",,,andrew@jacandacapital.com.au,1
,Hugh Mason,,@hughmason,http://www.linkedin.com/in/hughmason,,"Following a degree in Physics, Hugh trained as a science TV producer on the BBC's live primetime science show, Tomorrow's World. Eight million viewers tuned in every week hoping that at least one of the demonstrations would go wrong. Hugh's items on the show frequently gave them what they wanted.",,,hugh@jfdi.asia,1
,Ong Chiah Li ,,@chiahli,http://www.linkedin.com/in/chiahli,,,,,chiahli@jfdi.asia,1
,Anders Johansson,,,http://www.linkedin.com/pub/anders-c-johansson/3/6b6/7b4,,,,,johanssongroup@gmail.com,1
,Peter Wittmann,,,,,,,,peter@jpinco.com,1
,Amit Anand,,@amitvedanand,http://www.linkedin.com/pub/amit-anand/3/290/6b7,,"Has over 14 years of active career in go-to-market strategies and corporate development for start-ups and corporations alike. Management, Leadership positions at Progress Software, Fiorano Software and Tata Infotech. Also started and concluded a trade sale of an animation and gaming business, ettaminA studios in India",,,amitvedanand@gmail.com,1
,Jayesh Parekh ,,@JayeshParekh,http://www.linkedin.com/pub/jayesh-parekh/0/35/726,,,,,jayeshparekh50@gmail.com,1
,Ali Mirza,,,http://www.linkedin.com/pub/ali-mirza/0/b88/88b,,"18 years experience across the Asia Pacific with strong focus on India, China and S.E. Asia as well as the Middle East. ",,,ali@kae-capital.com,1
,Noritaka Araki,,@okura324,http://www.linkedin.com/pub/noritaka-araki/4a/8b1/160,,,,,n-araki@kamiol.co.jp,1
,Norihito Ishikawa ,,,http://www.linkedin.com/pub/norihito-ishikawa/24/7b4/318,,,,,n-ishikawa@kamiol.co.jp,1
,Vincent Lauria (Vinnie),http://www.vinnie.net/,@vlauria,http://www.linkedin.com/in/vincentlauria,,"He is currently mentoring and advising startups in a number of early stage incubators and investment funds and spent 2011 traveling around Asia, meeting with startups, investors, and budding entrepreneurs. He hosted events to help foster the startup ecosystem, such as SuperHappyDevHouse.sg with over 200 attendees from 7 different countries.",,,vincent.lauria@gmail.com,1
,Benjamin Ng,,,http://www.linkedin.com/pub/benjamin-ng/33/787/881,,,,,benjamin@linc360.com,1
,Magnus Jepson,,,,,"He has worked actively as a sourcing consultant since 2010 and has established an international network for his clients. Mr. Jepson has represented companies seeking to gain competitive advantage by purchasing components, raw materials, products or other elements from emerging markets such as China, Vietnam, Malaysia and Thailand, and in 2011 Mr. Jepson made the strategic decision to relocate to Singapore to better serve the needs of his clients.",,,mjepson@lionpartners.sg,1
,Christopher Angkasa,,,http://www.linkedin.com/in/angkasachris,,,,,angkasachris@gmail.com,1
,Theodore Ma ,,@theodorema,http://www.linkedin.com/in/theodorema,,"After graduating from Stanford in 2004, he has been leveraging his family's jewelry retail network and wholesale business, and extending them to the online world. These businesses include: MaBelle Jewellery, IAD Jewellery, MB Life.com, as well as other companies within The Lee Heng Diamond Group.",,,theodore.ma@gmail.com,1
,K.F. Seetoh,,,http://www.linkedin.com/in/kfseetohmakansutra,,,,,seetoh@makansutra.com,1
,Winston Quesang,,@DigitalCommando,http://www.linkedin.com/in/winstonquesang,,"As an aspiring technopreneur with a solid passion for continuous learning in the areas of technology, marketing and management innovations, he graduated his degree in Masters of Technology Management in University of the Philippines, Diliman. Not that he graduated with flying colors, but was able to come-up with his own strategic scenario planning framework in creating a winning Digital Ecosyste",,,winstonquesang@gmail.com,1
,Simon Meers ,,@simonmeers,http://www.linkedin.com/pub/simon-meers/11/527/3a4,,"He has over 18 years of investment and finance experience across three different geographic regions. He is currently Principal and Chief Investment Officer for Matinda Capital, an Investment Company specializing in Venture Capital opportunities across Asia.",,,simon@matindacapital.com,1
,Michael Maltese ,,,http://www.linkedin.com/in/maltese,,,,,michael@matindacapital.com,1
,Arnie Chaudhuri ,,,http://www.linkedin.com/pub/arnie-chaudhuri/2/41/735,,"He has 14 years of experience in senior leadership positions covering mobile sales and distribution, channel development, marketing strategy, advertising and mobile applications. He is recognized as one of the leading experts in the mobile industry in Asia.",,,arnie.chaudhuri@mbounce.com,1
,Danny Oei wirianto ,,@dWirianto,http://www.linkedin.com/in/dannywirianto,,,,,danny@mindtalk.com,1
,Linus Koh ,,@linuskkoh,http://www.linkedin.com/pub/linus-koh/5/337/134,,,,,linus.koh@nutmeg.sg,1
,Paul Whiteway ,,,http://www.linkedin.com/in/paulwhiteway,,His career has included working in both corporate environments such as Microsoft and Yahoo as well as entrepreneurial start-ups in the US and the UK. This has equipped  with the unique ability to apply entrepreneurial thinking and creativity balanced with a structured and analytical approach to managing and scaling a business. ,,,paulwhiteway@gmail.com,1
,Christian Nicolas Kaas ,,,http://www.linkedin.com/in/ckaas,,"Educated in France and the United States, he has been based in China for most of the last 6 years, both as a student and as a consultant in a pan-Asian career that has brought him close to the public utilities, oil and gas and telecoms sectors.",,,christiankaas@gmail.com,1
,Tom Strodtbeck ,,,http://www.linkedin.com/pub/tom-strodtbeck/2/873/683,,,,,tstrodtbeck@nbia.org,1
,James Chan,,@m0t0chan,http://www.linkedin.com/in/motochan,,"He was awarded a full overseas scholarship by the Singapore Government in 2000, and after completing 2.5 years of military service in an Armored Battalion as a Combat Medic, spent 4 years in the US to graduate with Bachelors from Carnegie Mellon in 2005 with a double major in Electrical & Computer Engineering and Engineering & Public Policy, and from Stanford in 2006 with Masters in Management Science and Engineering.",,,james@neotenylabs.com,1
,John Berns ,http://www.johnberns.com/,@jfxberns,http://www.linkedin.com/in/jfxberns,,,,,jfxberns@gmail.com,1
,Upal Basu ,,,http://www.linkedin.com/pub/upal-basu/0/3a/9b9,,"20 years of experience: Venture Capital, Entrepreneur, Business and Corporate Development, Management Consulting, Engineering",,,upal.basu@nokia.com,1
,Chieh Suang Khor ,,,http://www.linkedin.com/in/chiehsuang,,,,,chieh.suang@gmail.com,1
,Karen Koh,,,,,,,,karen.koh@nutmeg.sg,1
,Hiro Maeda,,,,,,,,hiro@onlab.jp,1
,John Tan ,,@therealjohntan,http://www.linkedin.com/in/therealjohntan,,,,,john.tan@startupjunkie.sg,1
,Trapp Lewis ,,,http://www.linkedin.com/in/trapplewis,,Senior executive / leader with over 15 years international experience focused on performance and the bottom lin,,,TRAPPLEWIS@GMAIL.COM,1
,Kevin Chen,,,http://www.linkedin.com/pub/kevin-chen/1/810/4ba,,,,,kevinchen@pinehurstadvisors.com,1
,Wayne Soh ,,,http://www.linkedin.com/in/waynesoh,,"Wayne has been active in the local technology and startup ecosystem in Singapore as one of the leading members of The Digital Movement. He has led and managed teams to run events like Nexus 2007, iX Conference and Global Speednetwork between Silicon Valley and Singapore. He has also conceived and led the organization of the Tertiary Tech Conference for local universities in Singapore.",,,wayne@plugandplaytechcenter.com,1
,Mark Greig ,,@mark_greig,http://www.linkedin.com/in/markgreigelevationcapital,,,,,mark@pollenizer.com,1
,Phil Morle ,,@philmorle,http://www.linkedin.com/in/pmorle,,"Before Pollenizer, he was the CTO at Kazaa for 5 years and led the development of a technology strategy which saw 5 million users online at any one time, millions of downloads per day and a total global user base of over 100 million, all this powered by innovative technology, a globally distributed team and a sprinkling of imagination.",,,phil@pollenizer.com,1
,Gareth P. Walker ,,,http://www.linkedin.com/in/garethpoh,,,,,gareth@prestonwalker.com,1
,Rico Wyder ,http://www.thesiliconroad.com/,@ricowyder,http://www.linkedin.com/in/ricowyder,,,,,rico.wyder@gmail.com,1
,Axel Favre ,,,http://www.linkedin.com/pub/axel-favre/13/101/582,,"MBA professional with extensive international experience and strong sales and marketing background equipped to identify attractive industry sectors and specific companies for investment, quickly comprehend technology trends and business models, communicate effectively with entrepreneurs, and deploy skills highly applicable to contributing to a venture- capital or private-equity firm",,,axel@reddotventures.com,1
,Adil Hussain,,,,,,,,adil@reddotventures.com,1
,Ari Klinger ,,@Ariklinger,http://www.linkedin.com/in/ariklinger,,"Extensive experience in starting, building and selling Internet-related businesses. Co-founder and CEO of iMega, an online media network with over 30 million visitors a month, sold to a listed marketing services group in 2006.",,,ari.klinger@rightclickcapital.com,1
,Henry Tang,,,http://www.linkedin.com/in/henrytang,,"Previous buyside experience in financial services (banks, consumer finance, insurance and wealth management) in UK, Europe, MENA and Asia-Pacific.",,,henry.l.tang@gmail.com,1
,Blaise Rattana ,,@itsblaise,http://www.linkedin.com/in/vbrattana,,"Results-driven Management Consultant with notable success directing and participating in a broad range of technology solution implementations and strategies for product development, integration services, and customer engagements. Performance-driven as a hands-on leader and self-starter in leading all stages of product and software development life cycles with specialty in web technologies. Disciplined in interpersonal communication for managing collaborative teams across globally diverse and cross-functional groups at all organizational levels.",,,blaise.rattana@gmail.com,1
,Sunny Patel,,,http://www.linkedin.com/in/sunpat,,"Buy-Side Investment professional with 10+ experience, primarily focused on Alternative Investments including Venture Capital, Private Equity, Hedge Funds, and Real Estate.Sunny has worked in New York, Toronto, and London in Finance (Alternative Investments) and was part of the Investment Team (Buy-Side) at GAM, overseeing $28 Billion in Investments before co-founding Seashell Venture Partners to invest in early stage growth companies in multiple industries.",,,sunny@seashellvc.com,1
,Suman Balani ,,@sumanbalani,http://www.linkedin.com/pub/suman-balani/21/473/9ba,,"Business leader with over 15 years experience in senior management positions spanning the Financial, Technology and Healthcare services sectors. Proven track record in building new businesses, managing complex projects, driving process transformation and change, marketing, PR and brand development.",,,suman.balani@shengainternational.com,1
,Namek Zu'bi,,@namekz,http://www.linkedin.com/in/namekzubi,,,,,namek@siliconbadia.com,1
,Thomas Anderegg,,,http://www.linkedin.com/pub/thomas-anderegg/17/946/457,,"Investment executive, with 18 years of investment experience.Has been managing teams of investment professionals for many years and gained international experience with career stages in Zurich, Hong Kong and Singapore.",,,thomas.anderegg@silverseaam.com,1
,Axel Ritter,,,http://www.linkedin.com/pub/axel-ritter/38/438/a6a,,"He has over 22 Years of experience in the financial industry with senior positions held in Deutsche Bank Wealth Management and UBS Wealth Management. Over his career he has established a proven and respected track record in designing and managing discretionary portfolios of funds for large private individuals which have substantially outperformed benchmarks. In the latter part of his career, Axel has been dedicated to the selection, due diligence, approval and marketing of Alternative Investment products including Hedge funds, Commodities products, Private Equity and Real Estate solutions.",,,axel.ritter@silverseaam.com,1
,Lennel Tan,,,http://www.linkedin.com/pub/lennel-tan-%E9%99%88%E5%BB%BA%E8%89%AF%EF%BC%89/1/a61/79b,,"Currently working as marketing manager for SingTel Innovation Exchange's partner programme for 3rd party developers, focusing on programme marketing and promoting the adoption of innovative solutions. I also run myBusiness techblog - an ICT blog dedicated to the sharing of business innovation and technology news for Small and Medium Enterprises in Singapore.",,,lenneltan@singtel.com,1
,Eunice Yue,,,http://www.linkedin.com/pub/eunice-yue/16/414/454,,,,,euniceyue@singtel.com,1
,Jim Tay,,@Jimtaykh,http://www.linkedin.com/pub/jim-tay/3/563/aba,,,,,jimtay@singtel.com,1
,Aaron Tan Wei Cheng,,,,,,,,aarontwc@singtel.com,1
,Monica Tsai,,@tsai_monica,http://www.linkedin.com/pub/monica-tsai/0/564/ab4,,,,,Monica@singtel.com,1
,Hieu Nguyen,http://blog.ngochieu.com/,@ngochieu,http://www.linkedin.com/in/ngochieu,,He has 12 years of experience in ICT Industry  and 6 years in management level for International ICT companies,,,hieu@skynet.vn,1
,Anna Lo,,@annalo_sb,http://www.linkedin.com/in/annaylo,,"Manager and co-founder of Softbank's Bodhi fund, focusing on early-stage companies in China, India and selected Southeast Asia geographies.",,,alo@softbankci.com,1
,Antti Ylimutka,,@andynosebone,http://www.linkedin.com/pub/antti-ylimutka/27/5b0/752,,,,,antti@startupsauna.com,1
,Ilkka Kivimäki,,@ilkkakivimaki,http://www.linkedin.com/pub/ilkka-kivim%C3%A4ki/0/4a/272,,,,,jevgeni.peltola@gmail.com,1
,Jevgeni Peltola,,@EvgPe,http://www.linkedin.com/in/peltola,,,,,jevgeni.peltola@gmail.com,1
,Clint Nelsen,http://clintnelson.com/,@clintnelsen,http://www.linkedin.com/in/clintnelsen,,"Clint is passionate about startups and technology. He regularly serves as a lecturer on entrepreneurship & startups at universities such as Stanford. Clint loves serving as a mentor at entrepreneurial events & startup accelerators, advising tomorrow's startup talent.",,,clint@startuplabs.org,1
,Josh (Yoshihiko) Shizu,,,http://www.linkedin.com/pub/josh-yoshihiko-shizu/1/115/38b,,,,,yoshihiko.shizu@sumitomocorp.co.jp,1
,William Henley,,@WilliamBotak,http://www.linkedin.com/in/williamhenley,,"He has been operating in the capital markets since 1995. Broad range of exposure from retail equity sales, institutional sales, institutional sales trading, corporate advisory, investment banking, merger & acquisition and private banking. ",,,william.henley@gmail.com,1
,William Robert Smith,,,,,,,,bizmorph@yahoo.com,1
,Sally Hall,,,,,,,,s.hall@guthriecastle.com,1
,Daniel Steven Pena Sr,,,,,,,,LairdPena@guthriecastle.com,1
,Tiffany Wu,,,http://www.linkedin.com/pub/yun-ruey-tiffany-wu/4/614/80,,,,,tiffany.wu@tmi.vc,1
,Mark Hsu ,,@markhsu,http://www.linkedin.com/in/markhsu,,,,,mark.hsu@tmi.vc,1
,David Gowdey ,,@gowdey,http://www.linkedin.com/in/gowdey,,"An experienced investor and seasoned corporate development executive in the digital media industry, particularly within the world's emerging geographies, such as Indonesia, Russia, India and the Middle East. Successfully completed numerous transactions (acquisitions, investments, joint ventures) around the globe and has cultivated a large vibrant network throughout the media, Internet, venture capital, investing and start-up space.",,,dgowdey@tpg.com,1
,Brian Wee,,,http://www.linkedin.com/pub/brian-wee-ca/1/702/b31,,,,,brianwee7@gmail.com,1
,James Lee,,,http://www.linkedin.com/pub/james-lee/4/1a7/72a,,"3 years experience starting up a financial services company focusing on SME lending in key Central China markets covering Sichuan, Chongqing and Hubei provinces.Specialised in corporate planning, loan product structuring and business development.",,,jlee@vertexmgt.com,1
,Terence Sim ,,,http://www.linkedin.com/pub/terence-sim/1a/180/888,,,,,terence.sim@vickersinvest.com,1
,To Ninh Nguyen,,,,,,,,lam@agilish.com,1
,Christopher Zobrist ,,,http://www.linkedin.com/in/czobrist,,,,,czobrist@gmail.com,1
,B. Paul Santos ,,,http://www.linkedin.com/pub/b-paul-santos/2/a05/b18,,"Experienced entrepreneur and early stage investor. Has co-founded six companies across different industries and exited twice. Currently leading the Asian office of an early stage, cross-border venture capital fund and its affiliated incubator. Both invest in start-ups in digital media, technology and technology-enabled services that target the US, Southeast Asia, India and China.",,,paul@wavemakerlabs.com,1
,Debneel Mukherjee ,,,http://www.linkedin.com/in/debneel,,"Finance professional with in depth knowledge and experience in banking, finance and accounting, besides successfully running start-up ventures in technology. Interested in early stage startups and Company's 'on the bubble', he has the ability to overcome complex business challenges and make high-stakes decisions using experience-backed judgment, strong work ethic and irreproachable integrity. Respected as a proponent of empowerment and enablement, rather than entitlement.",,,debneel@wavemakerlabs.com,1
,Craig Hewett ,,@Craigspot,http://www.linkedin.com/pub/craig-hewett/1/b4b/326,,"He has over 15 years experience in the online travel distribution industry, starting out with Holiday Inn Worldwide (now known as InterContinental Hotels Group) back in 1995 when the company launched the world's first online booking engine. He left Holiday Inn Worldwide in 1999 to join the start up team for Priceline.com in Asia. He then joined the start up team for Zuji in Singapore where his tenure was cut short by the events of September 11th 2001.",,,craig@wego.com,1
,Ross Veitch ,,@rossveitch,http://www.linkedin.com/pub/ross-veitch/28/192/165,,,,,ross@wego.com,1
,Joanne Huang,,,http://www.linkedin.com/in/joannehuangtw,,"MBA graduate with international exposure as well as past professional experiences in VC/PE, Marketing/PR, and Management Consulting.",,,northstarjojo@me.com,1
,Asim Qureshi ,,@asim0307,http://www.linkedin.com/in/asimiqureshi,,"He brings 14+ years of telecom, IT & media experience, designing & delivering web, voice and data services for some of the leading companies & mobile operators across the globe.",,,asim1976@gmail.com,1
,Sanjeev Shah,,,http://sg.linkedin.com/pub/sanjeev-shah/3/783/a1,,,,,sanjeev@bafspectrum.com,1
,Peter Widjaja ,,@pwidjaja007,http://www.linkedin.com/pub/peter-widjaja/36/327/482,,,,,Peter.Widjaja@east.vc,1
,Michiel Wind ,,,http://www.linkedin.com/pub/michiel-wind/47/708/68,,,,,jennylaw.sg@gmail.com,1
,Chandra Tjan ,,@chandratjan,http://www.linkedin.com/pub/chandra-tjan/27/986/22a,,,,,chandra.tjan@east.vc,1
,Calvin Kizana ,,@CalvinKizana,http://www.linkedin.com/in/calvinkizana,,"A serial entrepreneur, strategist and proven professional IT consultant backed by strong technical and analytical skills as well as creative and innovative with more than 10 years extensive experience in mobile industry, internet space, and wireless technology with implementation on local and global scale.",,,calvin.kizana@elasitas.com,1
,Vishwas Nadig ,,@vishwasnadig,http://www.linkedin.com/pub/vishwas-nadig/2/362/691,,,,,vishwas.nadig@gemalto.com,1
,Sieng Van Tran ,,@sieng,http://www.linkedin.com/in/sieng,,,,,sieng@fold7.com,1
,Rupert von Seidlein ,,,http://www.linkedin.com/in/rseidlein,,,,,rseidlein@gmail.com,1
,Evie Zhongyu Zhang,,,http://www.linkedin.com/pub/evie-zhongyu-zhang/21/a12/84a,,,,,ezhang@vertexmgt.com,1
,Kalyan Krishnamurthy ,,,,,,,,kalyan@tigerglobal.com,1
,Renee Tang,,@reneetang_5,,,,,,reneetang@pacificplace.co.id,1
,William Gomez,,,,,,,,gowilliammez@gmail.com,1
,Harry Heng,,,,,"He has 12 years of corporate planning and international business development experience working in a listed Singapore-HQ MNC as well as 6 years in strategic and general management positions in promising new companies in the engineering and technology sectors. He was the founding member and Senior Vice President of a water treatment company with presence in both the United States and Singapore. Prior to that, he held concurrent roles as corporate planner, business development and investment manager in the marine division of Singapore Technologies Engineering, and the general manager of one of its subsidiary, STSE Engineering Services Pte. Ltd.",,,harry@mercatus-capital.com,1
,Yunfei Jia (Jimmy),,,sg.linkedin.com/pub/yunfei-jia/16/2a/ab4,,"He is actively involved in various sectors with keen interest in Healthcare, Information and Telecommunications, and Interactive Digital Media. He is also part of the mentorship team under the Spring Incubator program. Prior to Mercatus, he worked at Dulwich College Management International as a finance analyst in Shanghai where he focused on new business development and financing",,,jimmy@mercatus-capital.com,1
,EK Liang Lim,,,,,,,,intersis@centrin.net.id,1
,Henry Chan,,,http://www.linkedin.com/pub/henry-chan/a/925/949,,,,,henry@humannetworklabs.com,1
,James Yang ,,,http://www.linkedin.com/pub/james-yang/6/20b/8b8,,,,,wh.yang@mediatek.com,1
,John Chang,,,http://www.linkedin.com/pub/john-chang/1b/826/244,,,,,john@worldoncloud.com,1
,Ming Shen Cheo ,http://www.bossming.com/,@bossming,http://www.linkedin.com/pub/ming-shen-cheo/4/384/531,,,,,ming@netccentric.com,1
,Louis Chua ,,@lemms,http://www.linkedin.com/in/louischua,,,,,bcchua@starhub.com,1
,Erwin Suganda ,,,,,,,,erwins@ubsgold.com,1
,Chade-Meng Tan ,,@chademeng,http://www.linkedin.com/pub/chade-meng-tan/0/11b/bb7,,,,,chademeng@gmail.com,1
,Tralvex Yeap,,,,,,,,jennylaw@bansea.org,1
,Yen-Lu Chow ,,,http://www.linkedin.com/pub/yen-lu-chow/0/164/6b4,,"She spans 30 years in the tech, media, and venture capital industry, including management and leadership capacities in multinational companies, research institutions, as well as start-ups. Over past 16 years, he has been active in venture creation and company building: starting companies, turning around troubled ones, building teams and organizations, and as an investor, advisor and mentor to budding new ventures.",,,jennylaw@bansea.org,1
,Balaji Venkatesan ,,,http://www.linkedin.com/pub/balaji-venkatesan/2/409/346,,,,,balaji.venkatesan@internationalsos.com,1
,Sang Uh Han,,,,,,,,shan@vertexmgt.com,1
,Shaun Ting,,,,,,,,sting@tingcapital.com,1
,Paul Southern,,,http://www.linkedin.com/in/paulsouthern,,A veteran of the telecom and media industry with over 20 years' experience in senior roles at both multi-nationals and startups. Now leading Southeast Asia for Radical Company which builds brands and markets through a pervasive digital experience.,,,paul@pasoco.biz,1
,Volker Heistermann,,,http://www.linkedin.com/in/volkerheistermann,,"Lived in Silicon Valley for over 15 years and in Taiwan since 2010. Started first business in Germany in the 90s and founded Yushan Ventures in 2011, a startup advisory and accelerator program in Taipei. Lived and worked on three continents (Europe, Asia, North America).",,,volker_heistermann@hotmail.com,1
,Raffy Montemayor,,,http://www.linkedin.com/in/raffymontemayor,,"Exceptional success in exceeding target revenue and customer base goals by developing and executing innovative sales and marketing strategies and new product or feature launches. Extensive experience conducting market research and business analyses in order to identify and capitalize on market opportunities with the greatest ROI potential. Superior leadership, communication, presentation, interpersonal and collaborative teamwork skills, including forging and cultivating relationships with internal stakeholders and key external partners. Outstanding experience in working within diverse cultures; comfortable with groups from small to big, and with people on all levels in an international organization, including executive leadership",,,raffy.montemayor@insead.edu,1
,Edmund Yong,,,http://www.linkedin.com/pub/edmund-yong/8/27/588,,,,,edmundyong@accel-x.com,1
,Liang Jian Tan,,,http://www.linkedin.com/pub/liang-jian-tan/19/568/100,,",",,,liangjian@singtel.com,1
,Christy Lee,,,http://www.linkedin.com/in/christylsw,,,,,christy@vic.org.my,1
,Farhan Yaqub,,@farhanyaqub,http://www.linkedin.com/in/farhanyaqub,,Working closely with the Singapore Government to incubate and invest in early stage tech start-ups across Asia,,,farhan@neotenylabs.com,1
,Yvonne Kwek,,,http://www.linkedin.com/pub/yvonne-kwek/25/600/682,,,,,Yvonnekwek@singtel.com,1
,Patrick Adhiatmadja,,,http://www.linkedin.com/pub/patrick-adhiatmadja/1/398/ab7,,,,,patrick@principia.co.id,1
,Hock Chuan Tam,,,,,,,,hctam@singtel.com,1
,Jeffrey Paine,,@jpaine,http://www.linkedin.com/in/jeffreypaine,,,,,jeff@battleventures.com,1
,Malik Al Madani,,,http://www.linkedin.com/pub/malik-al-madani/17/7/842,,,,,malik.almadany@gmail.com,1
,Grace Quek,,,http://www.linkedin.com/pub/grace-quek/7/54/190,,,,,huanhui@gmail.com,1
,Ben Gillenwater,,@bgilly,http://www.linkedin.com/in/bgilly,,A business savvy technology executive who is currently focused on mobile device ecosystems in the Asia Pacific region,,,bgillenwater@rim.com,1
,Tudor Coman,,@TheTwoDoor,http://www.linkedin.com/in/tudorcoman,,,,,tcoman@rim.com,1
,Jon Song,,,,,,,,jonsongjf@yahoo.com,1
,Yasser Al Bahandy,,,http://www.linkedin.com/pub/yasser-al-bahandy-cdcm/b/316/903,,,,,y.albahandy@gmail.com,1
,Clarence Tan,,,http://www.linkedin.com/pub/clarence-tan/2/2a7/a56,,,,,cktan@ieee.org,1
,Chieh Suang Khor,,,http://www.linkedin.com/in/chiehsuang,,,,,cskhor@nusantaraventures.com,1
,Mun Sean Leong,,@MunSean,http://www.linkedin.com/pub/mun-sean-leong/2/990/734,,,,,munsean@clearpoint.com.my,1
,Kenny Yong Foo Ken,,,,,,,,kenny@clearpointpartners.com.my,1
,Beng Eu Lim,,,http://www.linkedin.com/pub/beng-eu-lim-cfa/15/25/b66,,,,,julian@clearpointpartners.com.my,1
,Weng Wai Koh,,@wengster,http://www.linkedin.com/pub/weng-wai-koh/1/5ba/528,,"He trained as programmer, specialized in systems & networks and managed the execution of key projects. He found his calling in client servicing and soon began his journey in the telco world. He has serviced DiGI, P1, U-Mobile, PT Berca and Maxis. He now plies his trade in the digital and media industry. Other key clients Weng is working with or has worked with in the past include P&G, Toyota, Volkswagen, BVI, ICI, Bayer, Colgate and Microsoft. To date, he has spent more than 10 years in the digital and technology world. ",,,wengwai.koh@groupm.com,1
,Basil Darwish,,@badarwish,http://www.linkedin.com/in/basildarwish,,,,,basil.a.darwish@gmail.com,1
,Ashwin Sani,,,,,,,,ashwins@hk.super.net,1
,Honby Kurniawan,,@honbyk,http://www.linkedin.com/in/honbyk,,,,,honby@xanggar.com,1
,Arnie Chaudhuri,,,http://www.linkedin.com/pub/arnie-chaudhuri/2/41/735,,"Arnie has 14 years of experience in senior leadership positions covering mobile sales and distribution, channel development, marketing strategy, advertising and mobile applications. He is recognized as one of the leading experts in the mobile industry in Asia. ",,,arnie.chaudhuri@mbounce.com,1
,Hannah Nguyen,,,,,"Prior to her move to Singapore, Hannah served as the head of sales and marketing at Webtretho, the premier online community in Vietnam. Hannah was in charge of driving sales and educating business partners about online advertising opportunities. Striving to take the digital ecosystem of Vietnam to the next level, Hannah played an active role as the member of Vietnam Internet Advertising Bureau steering committee and worked hand in hand with leading agency and advertiser representatives to make online media planning and purchasing more efficient and transparent. Earlier in her career, Hannah held positions at Parnassus Investment, a US$ 4bn investment fund in San Francisco dedicated to supporting sustainable companies with outstanding ethical and social responsibility standards.",,,hannah@digitalmedia.vc,1
,Daniel Teng,,,,,,,,jason.tengty@gmail.com,1
,Kenny Teng,,,,,,,,jason.tengty@gmail.com,1
,Abhilash Tripathi,,,http://www.linkedin.com/in/abhilashtripathi,,,,,abhilash@gitpx.com,1
,Swaminathan Sekar,,@swammit,http://www.linkedin.com/profile/view?id=2013502&authType=NAME_SEARCH&authToken=G0i2&locale=en_US&srchid=392dbf17-8ab3-4bb9-bcd4-42fa973343ef-0&srchindex=1&srchtotal=1&goback=%2Efps_PBCK_Swaminathan%09Sekar++intel_*1_*1_*1_*1_*1_*1_*2_*1_Y_*1_*1_*1_false_1_R_*1_*51_*1_*51_true_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&pvs=ps&trk=pp_profile_photo_link,,,,,swaminathan.sekar@intel.com,1
,SP Yong,,,,,,,,sp.yong@yahoo.com,1
,Jackson Chan,,,http://www.linkedin.com/in/jacksonchan,,"He has a background in Corporate Strategy and Corporate Development with experience in Business Development, Strategic Planning, China Joint Venture project, Financial and Operational due diligence and quantitative financial modeling.",,,jackson.chan@anmedia.co.uk,1
,Francis Perrin,,,,,,,,francis2.perrin@orange-ftgroup.com,1
,Hiroshi Nishikawa,,,,,,,,hiroshi.nishikawa@orange-ftgroup.com,1
,Hugh Mason,,@hughmason,http://www.linkedin.com/in/hughmason,,"Born in the UK and now living in Singapore, Hugh co-founded JFDI.Asia, a seed accelerator program with a 60% success rate taking groups of entrepreneurs from idea to investment in 100 days. JFDI.Asia is building an innovation academy: a community of practitioners who accelerate, finance and teaching innovation.",,,hugh.mason@jfdi.asia,1
,Nick Rosa,,,http://www.linkedin.com/pub/nick-rosa/2/2a5/a1b,,"A former CEO and currently an investor who helps early stage companies create, build and grow their businesses. In addition to founding Sandbox Industries Nick was one of the Founders of Excelerate Labs.",,,nick@sandboxindustries.com,1
,Nina Nashif,,@NinaNashif,http://www.linkedin.com/in/ninanashif,,"A well-known thought leader and very passionate about stimulating innovation in the healthcare industry and supporting entrepreneurship across sectors. She is a frequent speaker on these topics at conferences and events around the world. She is also a member of the International Women’s Forum, on the Life Sciences Advisory Board of Springboard and involved in local civic organizations that support education, women and children.",,,nina@sandboxindustries.com,1
,Boris Polenske,,,http://www.linkedin.com/in/borispolenske,,,,,bpolenske@klickventures.com,1
,Felix Lam,,,http://www.linkedin.com/pub/felix-lam/0/200/a62,,,,,ftlam@me.com,1
,Hayato Takano,,,http://www.linkedin.com/pub/hayato-takano/5/52a/257,,,,,takano.hayato@adways.net,1
,Sinartus Sosrodjojo,,@Sinartus,http://www.linkedin.com/in/sinartus,,"He brings over a decade of design and photo-based visual communication skills and teaching experience to the table. His experiences in national and international media, sales communications and teaching had taught him that transparency is the key to success in any organization. Currently, he is serving as the Chief Operating Officer for Gilkor, a start-up focusing on creating a better experience for credit card users.",,,sinartus@gmail.com,1
,Kay-Mok Ku,,,http://www.linkedin.com/pub/kay-mok-ku/0/444/102,,,,,kaymok@gobivc.com,1
,Nurdhaniah Ahmad Shafri,,,http://www.linkedin.com/pub/nurdhaniah-ahmad-shafri/17/1/722,,,,,nurdhaniah@cradle.com.my,1
,Nazrin Hassan,,@NazrinHassan,http://www.linkedin.com/pub/nazrin-hassan/0/395/84a,,,,,norhanim@cradle.com.my,1
,Rubiah Abu Bakar,,,,,,,,shahidah@cradle.com.my,1
,Kelvin Goh,,,http://www.linkedin.com/pub/kelvin-goh/30/3b4/515,,,,,kelvin.goh@ch-investments.com.sg,1
,Willie Tan,,,,,,,,vincent@mrs.com.sg,1
,Kal Joffres,,@kaliper,http://www.linkedin.com/in/kalanga,,,,,kal@joffr.es,1
,Brian Koh,,,http://www.linkedin.com/pub/brian-koh/9/722/a0,,,,,briankoh@nus.edu.sg,1
,Tuff Yen,,,http://www.linkedin.com/pub/tuff-yen/0/10/299,,,,,tuff@seraphgroup.net,1
,Sandeep Casi,,@Cinemacraft,http://www.linkedin.com/pub/sandeep-casi/0/369/665,,,,,scasi@cinemacraft.tv,1
,Eduardo Saverin,,@edsaverin,http://www.linkedin.com/pub/eduardo-saverin/0/70a/31b,,,,,eduardo.saverin@gmail.com,1
,Abrar Ahmad,,,http://www.linkedin.com/profile/view?id=3973486&authType=NAME_SEARCH&authToken=qN8p&locale=en_US&srchid=5bd6820d-0bfe-47a4-99cb-fc9a038805dd-0&srchindex=2&srchtotal=230&goback=%2Efps_PBCK_Abrar%09Ahmad+_*1_*1_*1_*1_*1_*1_*2_*1_Y_*1_*1_*1_false_1_R_*1_*51_*1_*51_true_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&pvs=ps&trk=pp_profile_photo_link,,"He started in travel as the CIO of a leading travel technology firm followed by 9 years as the founder and CEO of a rapidly growing online travel agency.  He has hands on operational experience selling economy, luxury, corporate and wholesale travel in the US, UK, India, Singapore and S Africa. I've closed multi-million dollar deals with clients, secured countless air/hotel/car/cruise/travel content suppliers, managed key travel technology integrations across all major travel products and managed in-house, affiliate and online sales in 4 countries. ",,,abrara@travelcapitalist.com,1
,Tan Swee Yeong,,,,,"He founded UnrealMind Interactive Berhad in 2001, one of Malaysia’s fastest growing mobile content companies with a personal investment of RM300,000. In 2002, UnrealMind subsequently received venture capital funding of RM500,000 from MAVCAP, Malaysia’s largest ICT Venture Capital organisation.",,,sytan@pacmee.com,1
,Martin Hartono,,@tarm1n,http://www.linkedin.com/in/martinhartono,,,,,martin.b.hartono@gdpventure.com,1
,Pete Bonee,,,http://www.linkedin.com/pub/pete-bonee/3/56/808,,"25 years of leadership and entrepreneurial experience in  the networking and IT industries, and 3+ years of experience in early-stage venture investing.",,,pbonee@innosight.com,1
,Cheng Wei Ng,,@ngchengwei,http://www.linkedin.com/in/ngchengwei,,,,,chengwei@battleventures.com,1
,Rene Adhibrata,,@reneadhibrata,http://www.linkedin.com/pub/rene-adhibrata/26/4b1/2a9,,,,,rene.adhibrata@djarum.com,1
,Sean Bonner,http://blog.seanbonner.com/,@seanbonner,http://www.linkedin.com/in/seanbonner,,,,,sean@seanbonner.com,1
,Ian Ho,,,http://www.linkedin.com/in/ianhosoosiang,,,,,ian.ho@vickersventure.com,1
,Ivan Hudyana,,@Ivanhudy,http://www.linkedin.com/in/ivanhudyana,,,,,ivan.w.hudyana@djarum.com,1
,Joichi Ito,http://diving.ito.com/,@Joi,http://www.linkedin.com/in/joiito,,"He is on board of a number of non-profit organizations including The Mozilla Foundation and WITNESS. He has created numerous Internet companies including PSINet Japan, Digital Garage and Infoseek Japan and was an early stage investor in Twitter, Six Apart, Wikia, Flickr, Last.fm, Kongregate, Fotonauts/Fotopedia, Kickstarter and other Internet companies. He is the Guild Custodian of the World of Warcraft guild, We Know (http://weknow.to/). He is a PADI Master Scuba Diver Trainer, an Emergency First Responder instructor and a Divers Alert Network instructor.",,,joi@ito.com,1
,Kok Heng Kan,,,http://www.linkedin.com/pub/kok-heng-kan/22/237/488,,,,,kankh@rventurep.com,1
,Jerry Kasung,,,http://www.linkedin.com/pub/jerry-kasung/21/ba9/642,,,,,jerry.kasung@djarum.com,1
,Tai Le,,,http://www.linkedin.com/pub/tai-le/0/443/281,,,,,taile@temasek.com.sg,1
,Siew Hua,Lim,,,,,,,siewhua_lim@yahoo.com,1
,Hironori Maeda,http://hiromaeda.com/,@djtokyo,http://www.linkedin.com/in/hironorimaeda,,,,,heromaeda@gmail.com,1
,Kusumo Martanto,,,http://www.linkedin.com/in/kusumomartanto,,"Extensive knowledge and experience in Supply Chain Management. Certified in APICS Supply Chain Professional. Six sigma black belt certified with expertise in process improvement. Experience in developing Supply Chain Management strategy and vision, Enterprise Application Solution management/development as well as deployment.",,,kusumo.martanto@djarum.com,1
,Dave McClure,,@davemcclure,http://www.linkedin.com/in/davemcclure,,"A geek, startup investor, former software developer & entrepreneur, occasional tech blogger and internet marketing nerd.He lived in Silicon Valley for over 20 years and loved every minute. I'm the founding partner of 500 Startups (http://500.co), an Internet seed fund and startup incubator that has invested in ~400 companies all over the world including Twilio, SendGrid, TaskRabbit, and Wildfire Interactive (acqd by Google in 2012).",,,dave.mcclure@gmail.com,1
,Sandeep Murthy,,@sandeepm1,http://www.linkedin.com/pub/sandeep-murthy/0/28/ba,,,,,sandeep@sherpalo.com,1
,Murli Ravi,,@murli184,http://www.linkedin.com/in/murliravi,,,,,grace.goh@jafcoasia.com,1
,Joe Rouse,,,http://www.linkedin.com/in/jwsrouse,,"15 years’ experience in technology marketing, venture capital and consulting. Past operating roles include VP Business Development/COO of GridIron Software, Director of Marketing at Philsar Semiconductor (Acquired by Conexant) and Marketing roles at Tundra Semiconductor, from spin-out through IPO. In these roles, he worked closely with market leaders including Apple, Adobe, Cisco, IBM, Motorola, MSFT and Sun/Oracle.",,,jwsrouse@gmail.com,1
,Serena Siah,,@serenasiah,http://www.linkedin.com/in/serenasiah,,,,,serenasiah@hotmail.com,1
,C.K. Tan,,,,,,,,cktan@vertexmgt.com,1
,Meng Weng Wong,http://mengwong.livejournal.com/,@mengwong,http://www.linkedin.com/in/mengwong,,,,,mengwong@gmail.com,1
,Juanita Sabapathy,,,http://www.linkedin.com/pub/juanita-sabapathy/47/420/115,,,,,juanita.sabapathy@gmail.com,1
,Alvin Yong,,,,,,,,alvinyong@kpmg.com.sg,1
,Christopher Leong Yew Chong,,,,,,,,christopher@cradle.com.my,1
,Willie Foo,,,http://www.linkedin.com/pub/willie-foo/22/324/726,,,,,williefoo@mercatus-capital.com,1
